"""
OPTCG API — FastAPI backend
Validated against:
  - Render deployment docs (host 0.0.0.0, $PORT)
  - Pokemon TCG API response conventions
  - FastAPI + psycopg2 best practices

Endpoints:
  GET /                   — API info
  GET /sets               — all sets
  GET /sets/{id}/cards    — cards in a set
  GET /cards              — all cards with filters + pagination
  GET /cards/{id}         — single card + all sets it appears in
Docs: /docs  (Swagger UI auto-generated by FastAPI)
"""

import os
from typing import Optional
from contextlib import contextmanager
from fastapi import FastAPI, HTTPException, Query
from fastapi.middleware.cors import CORSMiddleware
import psycopg2
import psycopg2.extras
from dotenv import load_dotenv

load_dotenv()

app = FastAPI(
    title="OPTCG API",
    description="One Piece TCG card data — cards, sets, filters, binder support.",
    version="1.0.0",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["GET", "HEAD"],
    allow_headers=["*"],
)

# ── Database ──────────────────────────────────────────────────────────────────
# Connection-per-request is correct for Render free tier + Supabase session
# pooler. Render sleeps between requests so a persistent pool would be dropped
# anyway. Supabase's session pooler handles actual connection pooling server-side.

@contextmanager
def get_db():
    """Open a connection, yield cursor, always close on exit."""
    conn = psycopg2.connect(
        os.environ["DATABASE_URL"],
        cursor_factory=psycopg2.extras.RealDictCursor,
    )
    try:
        cur = conn.cursor()
        yield cur
    finally:
        conn.close()


def fetch(sql: str, params=None) -> list:
    with get_db() as cur:
        cur.execute(sql, params or [])
        return cur.fetchall()


def fetch_one(sql: str, params=None):
    with get_db() as cur:
        cur.execute(sql, params or [])
        return cur.fetchone()


# ── Routes ────────────────────────────────────────────────────────────────────

@app.get("/")
def root():
    return {
        "name":    "OPTCG API",
        "version": "1.0.0",
        "docs":    "/docs",
        "endpoints": [
            "GET /sets",
            "GET /sets/{id}/cards",
            "GET /cards",
            "GET /cards/{id}",
        ],
    }


@app.api_route("/sets", methods=["GET", "HEAD"])
def get_sets():
    """All sets, newest first."""
    rows = fetch("SELECT * FROM sets ORDER BY pack_id DESC")
    return {"count": len(rows), "data": rows}


@app.get("/sets/{set_id}/cards")
def get_set_cards(set_id: str):
    """All cards in a set, in card-ID order."""
    s = fetch_one("SELECT * FROM sets WHERE id = %s", [set_id.upper()])
    if not s:
        raise HTTPException(404, f"Set '{set_id}' not found")

    cards = fetch("""
        SELECT c.*
        FROM cards c
        JOIN card_sets cs ON cs.card_id = c.id
        WHERE cs.set_id = %s
        ORDER BY c.id
    """, [set_id.upper()])

    return {"set": s, "count": len(cards), "data": cards}


@app.get("/cards/{card_id}")
def get_card(card_id: str):
    """Single card by ID. Includes every set it appears in."""
    card = fetch_one("SELECT * FROM cards WHERE id = %s", [card_id.upper()])
    if not card:
        raise HTTPException(404, f"Card '{card_id}' not found")

    sets = fetch("""
        SELECT s.*
        FROM sets s
        JOIN card_sets cs ON cs.set_id = s.id
        WHERE cs.card_id = %s
        ORDER BY s.pack_id
    """, [card_id.upper()])

    return {**card, "sets": sets}


@app.api_route("/cards", methods=["GET", "HEAD"])
def get_cards(
    # --- filters ---
    set_id:    Optional[str]  = Query(None, description="Filter by set e.g. OP-01"),
    color:     Optional[str]  = Query(None, description="Red, Blue, Green, Purple, Black, Yellow"),
    category:  Optional[str]  = Query(None, description="Leader, Character, Event, Stage, Don"),
    rarity:    Optional[str]  = Query(None, description="Leader, Common, Uncommon, Rare, SuperRare, SecretRare"),
    name:      Optional[str]  = Query(None, description="Partial name search"),
    parallel:  Optional[bool] = Query(None, description="true=parallel only, false=base only"),
    min_power: Optional[int]  = Query(None, description="Min power"),
    max_power: Optional[int]  = Query(None, description="Max power"),
    min_cost:  Optional[int]  = Query(None, description="Min cost"),
    max_cost:  Optional[int]  = Query(None, description="Max cost"),
    # --- pagination (matches Pokemon TCG API convention) ---
    page:      int = Query(1,  ge=1,          description="Page number"),
    page_size: int = Query(50, ge=1, le=500,  description="Results per page (max 500)"),
):
    """
    Cards with optional filters. All filters are combinable.
    Pagination uses page/pageSize (same convention as Pokemon TCG API).
    """
    conditions, params = [], []

    if set_id:
        conditions.append(
            "EXISTS (SELECT 1 FROM card_sets cs WHERE cs.card_id = c.id AND cs.set_id = %s)"
        )
        params.append(set_id.upper())

    if color:
        conditions.append("%s = ANY(c.colors)")
        params.append(color.capitalize())

    if category:
        conditions.append("c.category ILIKE %s")
        params.append(category)

    if rarity:
        conditions.append("c.rarity ILIKE %s")
        params.append(rarity)

    if name:
        conditions.append("c.name ILIKE %s")
        params.append(f"%{name}%")

    if parallel is not None:
        conditions.append("c.parallel = %s")
        params.append(parallel)

    if min_power is not None:
        conditions.append("c.power >= %s")
        params.append(min_power)

    if max_power is not None:
        conditions.append("c.power <= %s")
        params.append(max_power)

    if min_cost is not None:
        conditions.append("c.cost >= %s")
        params.append(min_cost)

    if max_cost is not None:
        conditions.append("c.cost <= %s")
        params.append(max_cost)

    where  = ("WHERE " + " AND ".join(conditions)) if conditions else ""
    offset = (page - 1) * page_size

    total_row = fetch_one(f"SELECT COUNT(*) AS total FROM cards c {where}", params)
    total     = total_row["total"]

    cards = fetch(f"""
        SELECT c.*
        FROM cards c
        {where}
        ORDER BY c.id
        LIMIT %s OFFSET %s
    """, params + [page_size, offset])

    return {
        "count":      len(cards),
        "totalCount": total,
        "page":       page,
        "pageSize":   page_size,
        "data":       cards,
    }


@app.get("/images/{card_id}")
async def proxy_image(card_id: str):
    import httpx
    from fastapi.responses import Response
    url = f"https://en.onepiece-cardgame.com/images/cardlist/card/{card_id}.png"
    async with httpx.AsyncClient() as client:
        r = await client.get(url, headers={"Referer": "https://en.onepiece-cardgame.com/"}, follow_redirects=True)
    if r.status_code != 200:
        return Response(status_code=404)
    return Response(content=r.content, media_type="image/png", headers={"Cache-Control": "public, max-age=86400", "Access-Control-Allow-Origin": "*"})