UPDATE characters SET affiliation = 'A O Pirates', job = 'Pirate', status = 'Unknown' WHERE id = 1;
UPDATE characters SET epithet = 'Absalom of the Graveyard', fruit_name = 'Clear-Clear Fruit', fruit_type = 'Paramecia', affiliation = 'Thriller Bark Pirates ( Mysterious Four ) (former)', job = 'Reporter', status = 'Deceased' WHERE id = 2;
UPDATE characters SET epithet = 'Don Accino', fruit_name = 'Hot-Hot Fruit', fruit_type = 'Paramecia', affiliation = 'Accino Family', job = 'Patriarch', status = 'Alive' WHERE id = 3;
UPDATE characters SET fruit_name = 'Return-Return Fruit', fruit_type = 'Paramecia', affiliation = 'Neo Marines', job = 'Second-in-command of the Neo Marines', status = 'Alive' WHERE id = 5;
UPDATE characters SET affiliation = 'Shandia', status = 'Alive' WHERE id = 6;
UPDATE characters SET affiliation = 'Sun Pirates', job = 'Pirate', status = 'Alive' WHERE id = 8;
UPDATE characters SET affiliation = 'Marines', job = 'Captain', status = 'Alive' WHERE id = 9;
UPDATE characters SET affiliation = 'CP8', job = 'Cipher Pol Agent', status = 'Alive' WHERE id = 10;
UPDATE characters SET epithet = 'Iron Mace', fruit_name = 'Slip-Slip Fruit', fruit_type = 'Paramecia', bounty = '5,000,000', affiliation = 'Cross Guild', job = 'Pirate', status = 'Alive' WHERE id = 11;
UPDATE characters SET affiliation = 'Wagomuland', job = 'Heaven''s Gate Inspector (former)', status = 'Alive' WHERE id = 12;
UPDATE characters SET epithet = 'Diva Ann', fruit_name = 'Bijo-Bijo Fruit', fruit_type = 'Paramecia', job = 'Singer, Guest Announcer (former)', status = 'Alive' WHERE id = 17;
UPDATE characters SET affiliation = 'Kuja', job = 'Warrior (Former), Pirate', status = 'Alive' WHERE id = 18;
UPDATE characters SET fruit_name = 'Whisper-Whisper Fruit', fruit_type = 'Paramecia', affiliation = 'Warship Island', status = 'Alive' WHERE id = 19;
UPDATE characters SET fruit_name = 'Woods-Woods Fruit', fruit_type = 'Logia', bounty = '3,000,000,000', affiliation = 'Marines', job = 'Admiral', status = 'Alive' WHERE id = 20;
UPDATE characters SET epithet = 'Arlong the Saw', bounty = '20,000,000', affiliation = 'Arlong Pirates', job = 'Pirate Captain', status = 'Alive' WHERE id = 21;
UPDATE characters SET epithet = 'Strongest Monster of Kuri', affiliation = 'Mt. Atama Thieves', job = 'Bandit', status = 'Deceased' WHERE id = 22;
UPDATE characters SET affiliation = 'Marines ( SSG ) (former)', status = 'Alive' WHERE id = 23;
UPDATE characters SET epithet = 'Water Buffalo', affiliation = 'Whitebeard Pirates', job = '13th Division Commander', status = 'Alive' WHERE id = 24;
UPDATE characters SET epithet = 'Corrupt King', fruit_name = 'Isle-Isle Fruit', fruit_type = 'Paramecia', affiliation = 'Blackbeard Pirates', job = 'Titanic Captain (Captain of the Fourth Ship)', status = 'Alive' WHERE id = 25;
UPDATE characters SET fruit_name = 'Elephant SMILE', fruit_type = 'Artificial Zoan', affiliation = 'Beasts Pirates', job = 'Shinuchi', status = 'Alive' WHERE id = 26;
UPDATE characters SET fruit_name = 'Arms-Arms Fruit', fruit_type = 'Paramecia', affiliation = 'Happo Navy', job = 'Pirate', status = 'Alive' WHERE id = 27;
UPDATE characters SET fruit_name = 'Luck-Luck Fruit', fruit_type = 'Paramecia', affiliation = 'Gran Tesoro', job = 'Concierge', status = 'Alive' WHERE id = 28;
UPDATE characters SET fruit_name = 'Flying Squirrel SMILE', fruit_type = 'Artificial Zoan', affiliation = 'Beasts Pirates', job = 'Shinuchi', status = 'Alive' WHERE id = 29;
UPDATE characters SET epithet = 'Tyrant', fruit_name = 'Paw-Paw Fruit', fruit_type = 'Paramecia', bounty = '296,000,000', affiliation = 'Freedom Fighters (former)', job = 'Army Commander of the Revolutionary Army', status = 'Alive' WHERE id = 30;
UPDATE characters SET epithet = 'Bartolomeo the Cannibal', fruit_name = 'Barrier-Barrier Fruit', fruit_type = 'Paramecia', bounty = '200,000,000', affiliation = 'Barto Club', job = 'Captain of the Second Ship of the Straw Hat Grand Fleet', status = 'Unknown' WHERE id = 31;
UPDATE characters SET epithet = 'Magician', fruit_name = 'Straw-Straw Fruit', fruit_type = 'Paramecia', bounty = '320,000,000', affiliation = 'Hawkins Pirates', job = 'Pirate', status = 'Unknown' WHERE id = 32;
UPDATE characters SET epithet = 'Three-Headed Baskerville', affiliation = 'World Government ( Enies Lobby )', job = 'Chief Justices of Enies Lobby', status = 'Unknown' WHERE id = 33;
UPDATE characters SET epithet = 'Shark Cutter', bounty = '500,000,000', affiliation = 'Marines', job = 'Vice Admiral', status = 'Alive' WHERE id = 34;
UPDATE characters SET epithet = 'Earl Battler', bounty = '14,900,000', job = 'Poacher', status = 'Alive' WHERE id = 36;
UPDATE characters SET fruit_name = 'Hard-Hard Fruit', fruit_type = 'Paramecia', bounty = '11,600,000', affiliation = 'Trump Pirates', job = 'Pirate Captain', status = 'Alive' WHERE id = 37;
UPDATE characters SET affiliation = 'Marines (former)', job = 'Mikan Farmer', status = 'Deceased' WHERE id = 38;
UPDATE characters SET epithet = 'Bellamy the Hyena', fruit_name = 'Boing-Boing Fruit', fruit_type = 'Paramecia', bounty = '195,000,000', affiliation = 'Donquixote Pirates (former)', job = 'Dyer', status = 'Alive' WHERE id = 39;
UPDATE characters SET fruit_name = 'Pump-Pump Fruit', fruit_type = 'Paramecia', bounty = '457,000,000', affiliation = 'Revolutionary Army (East Army)', job = 'East Army Commander of the Revolutionary Army', status = 'Alive' WHERE id = 40;
UPDATE characters SET epithet = 'Benevolent King of the Waves', affiliation = 'Marines (GR 66)', job = 'Marine Captain', status = 'Alive' WHERE id = 41;
UPDATE characters SET affiliation = 'Red Hair Pirates', job = 'Pirate', status = 'Alive' WHERE id = 42;
UPDATE characters SET bounty = '1,500', affiliation = 'Heart Pirates', job = 'Pirate', status = 'Alive' WHERE id = 43;
UPDATE characters SET fruit_name = 'Bug-Bug Fruit, Model: Hornet', fruit_type = 'Zoan', affiliation = 'Tontatta Kingdom', job = 'Leader of Pink Bee Squad', status = 'Alive' WHERE id = 44;
UPDATE characters SET epithet = 'Big Pan the Wotan', affiliation = 'Foxy Pirates (former)', job = 'Pirate', status = 'Alive' WHERE id = 45;
UPDATE characters SET job = 'Priest (former)', status = 'Alive' WHERE id = 46;
UPDATE characters SET fruit_name = 'Grow-Grow Fruit', fruit_type = 'Paramecia', affiliation = 'Neo Marines', job = 'Marine Officer (former)', status = 'Alive' WHERE id = 47;
UPDATE characters SET affiliation = 'Poseidon', status = 'Alive' WHERE id = 48;
UPDATE characters SET bounty = '7,000,000' WHERE id = 50;
UPDATE characters SET fruit_name = 'Spider-Spider Fruit, Rosamygale grauvogeli Model', fruit_type = 'Ancient Zoan', bounty = '480,000,000', affiliation = 'Beasts Pirates ( Tobiroppo )', job = 'Shinuchi', status = 'Alive' WHERE id = 51;
UPDATE characters SET affiliation = 'Mokomo Dukedom', job = 'Guardian', status = 'Alive' WHERE id = 52;
UPDATE characters SET epithet = 'Blackbeard', fruit_name = 'Dark-Dark Fruit', fruit_type = 'Logia', bounty = '3,996,000,000', affiliation = 'Blackbeard Pirates', job = 'Pirate', status = 'Alive' WHERE id = 53;
UPDATE characters SET fruit_name = 'Pocket-Pocket Fruit', fruit_type = 'Paramecia', affiliation = 'Whitebeard Pirates', job = '6th Division Commander', status = 'Alive' WHERE id = 54;
UPDATE characters SET affiliation = 'Whitebeard Pirates', job = '9th Division Commander', status = 'Alive' WHERE id = 55;
UPDATE characters SET affiliation = 'Ideo Pirates', job = 'Martial Artist , Pirate', status = 'Alive' WHERE id = 56;
UPDATE characters SET fruit_name = 'Ride-Ride Fruit', fruit_type = 'Paramecia', bounty = '500,000,000', affiliation = 'Marines', job = 'Vice Admiral', status = 'Alive' WHERE id = 57;
UPDATE characters SET bounty = '14,300,000', affiliation = 'Bluejam Pirates', job = 'Pirate', status = 'Unknown' WHERE id = 58;
UPDATE characters SET fruit_name = 'Door-Door Fruit', fruit_type = 'Paramecia', affiliation = 'CP0', job = 'Cipher Pol Agent', status = 'Alive' WHERE id = 59;
UPDATE characters SET epithet = 'Snake Princess', fruit_name = 'Love-Love Fruit', fruit_type = 'Paramecia', bounty = '1,659,000,000', affiliation = 'Kuja Pirates ( Gorgon Sisters )', job = 'Captain of the Kuja Pirates', status = 'Alive' WHERE id = 60;
UPDATE characters SET fruit_name = 'Snake-Snake Fruit King Cobra Model', fruit_type = 'Zoan', bounty = '40,000,000', affiliation = 'Kuja Pirates ( Gorgon Sisters )', job = 'Ruler of Amazon Lily', status = 'Alive' WHERE id = 61;
UPDATE characters SET fruit_name = 'Snake-Snake Fruit Anaconda Model', fruit_type = 'Zoan', bounty = '40,000,000', affiliation = 'Kuja Pirates ( Gorgon Sisters )', job = 'Ruler of Amazon Lily', status = 'Alive' WHERE id = 62;
UPDATE characters SET bounty = '36,000,000', affiliation = 'Mogaro Kingdom', job = 'Assassin', status = 'Alive' WHERE id = 64;
UPDATE characters SET affiliation = 'Marines', job = 'Commissioned Marine Officer', status = 'Alive' WHERE id = 65;
UPDATE characters SET epithet = 'Bentham of the Wild', fruit_name = 'Clone-Clone Fruit', fruit_type = 'Paramecia', bounty = '32,000,000', affiliation = 'Newkama Land', job = 'Queen of Newkama Land', status = 'Alive' WHERE id = 66;
UPDATE characters SET affiliation = 'Red Hair Pirates', job = 'Pirate', status = 'Alive' WHERE id = 67;
UPDATE characters SET job = 'Mayor', status = 'Alive' WHERE id = 68;
UPDATE characters SET fruit_name = 'Glint-Glint Fruit', fruit_type = 'Logia', bounty = '3,000,000,000', affiliation = 'Marines', job = 'Admiral', status = 'Alive' WHERE id = 69;
UPDATE characters SET affiliation = 'Shandia', job = 'Shandia Warrior', status = 'Alive' WHERE id = 70;
UPDATE characters SET bounty = '100,000,000', affiliation = 'Marines', job = 'Commodore', status = 'Alive' WHERE id = 71;
UPDATE characters SET fruit_name = 'Gorilla SMILE', fruit_type = 'Artificial Zoan', affiliation = 'Beasts Pirates', job = 'Shinuchi', status = 'Alive' WHERE id = 72;
UPDATE characters SET epithet = 'Humming Brook', fruit_name = 'Revive-Revive Fruit', fruit_type = 'Paramecia', bounty = '383,000,000', affiliation = 'Straw Hat Pirates', job = 'Musician', status = 'Alive' WHERE id = 73;
UPDATE characters SET epithet = 'Brownbeard', bounty = '80,060,000', affiliation = 'Caesar Clown (defected), Centaur Patrol Unit (defected)', job = 'Leader of the Centaur Patrol Unit (former)', status = 'Alive' WHERE id = 74;
UPDATE characters SET epithet = 'Nyaban Brothers', bounty = '7,000,000', affiliation = 'Black Cat Pirates', job = 'Pirate Officer', status = 'Alive' WHERE id = 75;
UPDATE characters SET affiliation = 'Rocks Pirates (former)', job = 'Pirate (former)', status = 'Alive' WHERE id = 76;
UPDATE characters SET epithet = 'Master of Festivities', affiliation = 'Festival Pirates', job = 'Pirate Captain', status = 'Alive' WHERE id = 77;
UPDATE characters SET fruit_name = 'Spin-Spin Fruit', fruit_type = 'Paramecia', affiliation = 'Donquixote Pirates', job = 'Pirate Officer', status = 'Alive' WHERE id = 78;
UPDATE characters SET epithet = 'Buggy the Clown', fruit_name = 'Chop-Chop Fruit', fruit_type = 'Paramecia', bounty = '3,189,000,000', affiliation = 'Cross Guild', job = 'Pirate Captain', status = 'Alive' WHERE id = 79;
UPDATE characters SET affiliation = 'Thriller Bark Pirates', job = 'Surprise Zombie Boss', status = 'Deceased' WHERE id = 80;
UPDATE characters SET affiliation = 'Red Hair Pirates', job = 'Pirate', status = 'Alive' WHERE id = 81;
UPDATE characters SET affiliation = 'Revolutionary Army', job = 'Revolutionary', status = 'Alive' WHERE id = 82;
UPDATE characters SET epithet = 'World Destroyer', fruit_name = 'More-More Fruit', fruit_type = 'Paramecia', bounty = '500,000,000', affiliation = 'World Pirates', job = 'Pirate Captain', status = 'Unknown' WHERE id = 83;
UPDATE characters SET epithet = 'Cabaji the Acrobat', affiliation = 'Cross Guild', job = 'Pirate', status = 'Alive' WHERE id = 84;
UPDATE characters SET epithet = 'Master', fruit_name = 'Gas-Gas Fruit', fruit_type = 'Logia', bounty = '300,000,000', affiliation = 'NEO MADS', job = 'Scientist', status = 'Alive' WHERE id = 85;
UPDATE characters SET affiliation = 'Takoyaki 8 , Mermaid Cafe', job = 'Fashion designing apprentice', status = 'Alive' WHERE id = 86;
UPDATE characters SET epithet = 'Gang', fruit_name = 'Castle-Castle Fruit', fruit_type = 'Paramecia', bounty = '350,000,000', affiliation = 'Fire Tank Pirates', job = 'Pirate Captain', status = 'Alive' WHERE id = 87;
UPDATE characters SET affiliation = 'Foxy Pirates (former)', job = 'Pirate', status = 'Alive' WHERE id = 88;
UPDATE characters SET epithet = 'Wet-Haired Caribou', fruit_name = 'Swamp-Swamp Fruit', fruit_type = 'Logia', bounty = '210,000,000', affiliation = 'Caribou Pirates', job = 'Pirate Captain', status = 'Alive' WHERE id = 91;
UPDATE characters SET epithet = 'Phantom Thief', affiliation = 'Gran Tesoro', job = 'Thief', status = 'Alive' WHERE id = 92;
UPDATE characters SET epithet = 'Holy Mother', fruit_name = 'Soul-Soul Fruit', fruit_type = 'Paramecia', affiliation = 'Underworld', job = 'Child Trafficker', status = 'Deceased' WHERE id = 93;
UPDATE characters SET epithet = 'Fiery Carmen', job = 'Cook', status = 'Alive' WHERE id = 94;
UPDATE characters SET affiliation = 'Baratie', job = 'Charcutier', status = 'Alive' WHERE id = 95;
UPDATE characters SET affiliation = 'Mokomo Dukedom , Inuarashi Musketeer Squad', job = 'Ruler of Mokomo Dukedom', status = 'Alive' WHERE id = 96;
UPDATE characters SET epithet = 'Crescent Moon Hunter', fruit_name = 'Dog-Dog Fruit, Model: Nine Tailed Fox', fruit_type = 'Mythical Zoan', affiliation = 'Blackbeard Pirates', job = 'Titanic Captain (Captain of the Sixth Ship)', status = 'Alive' WHERE id = 97;
UPDATE characters SET epithet = 'Cavendish of the White Horse', bounty = '330,000,000', affiliation = 'Beautiful Pirates', job = 'Captain of the First Ship of the Straw Hat Grand Fleet', status = 'Alive' WHERE id = 98;
UPDATE characters SET affiliation = 'Thriller Bark Pirates', job = 'Wild Zombie', status = 'Deceased' WHERE id = 100;
UPDATE characters SET epithet = 'Chaka the Jackal', fruit_name = 'Dog-Dog Fruit, Model: Jackal', fruit_type = 'Zoan', affiliation = 'Arabasta Kingdom', job = 'Commander of Royal Guards', status = 'Alive' WHERE id = 101;
UPDATE characters SET affiliation = 'World Government ( Rosward Family )', job = 'World Noble', status = 'Alive' WHERE id = 102;
UPDATE characters SET epithet = 'Demon Lady', affiliation = 'Charlotte Family', job = 'Pirate Officer', status = 'Alive' WHERE id = 103;
UPDATE characters SET affiliation = 'Charlotte Family', status = 'Alive' WHERE id = 104;
UPDATE characters SET affiliation = 'Charlotte Family', job = 'Pirate Officer', status = 'Alive' WHERE id = 105;
UPDATE characters SET affiliation = 'Charlotte Family', job = 'Pirate Officer', status = 'Alive' WHERE id = 106;
UPDATE characters SET fruit_name = 'Mirror-Mirror Fruit', fruit_type = 'Paramecia', affiliation = 'Charlotte Family', job = 'Pirate Officer', status = 'Alive' WHERE id = 107;
UPDATE characters SET affiliation = 'Fire Tank Pirates', job = 'Cook', status = 'Alive' WHERE id = 108;
UPDATE characters SET affiliation = 'Charlotte Family', job = 'Pirate Officer', status = 'Alive' WHERE id = 109;
UPDATE characters SET epithet = 'Thousand Arms Cracker', fruit_name = 'Bis-Bis Fruit', fruit_type = 'Paramecia', bounty = '860,000,000', affiliation = 'Charlotte Family', job = 'Sweet Commander', status = 'Alive' WHERE id = 110;
UPDATE characters SET affiliation = 'Charlotte Family', job = 'Pirate Officer', status = 'Alive' WHERE id = 111;
UPDATE characters SET fruit_name = 'Puff-Puff Fruit', fruit_type = 'Paramecia', bounty = '300,000,000', affiliation = 'Charlotte Family', job = 'Pirate Officer', status = 'Alive' WHERE id = 112;
UPDATE characters SET affiliation = 'Charlotte Family', job = 'Pirates', status = 'Alive' WHERE id = 113;
UPDATE characters SET affiliation = 'Charlotte Family', job = 'Pirate Officer', status = 'Alive' WHERE id = 114;
UPDATE characters SET fruit_name = 'Butter-Butter Fruit', fruit_type = 'Paramecia', affiliation = 'Charlotte Family', job = 'Pirate Officer', status = 'Alive' WHERE id = 115;
UPDATE characters SET fruit_name = 'Mochi-Mochi Fruit', fruit_type = 'Special Paramecia', bounty = '1,057,000,000', affiliation = 'Charlotte Family', job = 'Sweet Commander', status = 'Alive' WHERE id = 116;
UPDATE characters SET epithet = 'Big Mom', fruit_name = 'Soul-Soul Fruit', fruit_type = 'Paramecia', bounty = '4,388,000,000', affiliation = 'Big Mom Pirates', job = 'Pirate Captain', status = 'Unknown' WHERE id = 117;
UPDATE characters SET epithet = 'Marriage Proposal Lola', bounty = '24,000,000', affiliation = 'Rolling Pirates', job = 'Pirate Captain', status = 'Alive' WHERE id = 118;
UPDATE characters SET epithet = 'Scribe', fruit_name = 'Book-Book Fruit', fruit_type = 'Paramecia', bounty = '120,000,000', affiliation = 'Charlotte Family', job = 'Pirate Officer', status = 'Alive' WHERE id = 119;
UPDATE characters SET affiliation = 'Charlotte Family', job = 'Pirate Officer', status = 'Alive' WHERE id = 120;
UPDATE characters SET fruit_name = 'Cream-Cream Fruit', fruit_type = 'Paramecia', affiliation = 'Charlotte Family', job = 'Pirate Officer', status = 'Unknown' WHERE id = 121;
UPDATE characters SET fruit_name = 'Heat-Heat Fruit', fruit_type = 'Paramecia', bounty = '300,000,000', affiliation = 'Charlotte Family', job = 'Pirate Officer', status = 'Alive' WHERE id = 122;
UPDATE characters SET fruit_name = 'Lick-Lick Fruit', fruit_type = 'Paramecia', bounty = '700,000,000', affiliation = 'Charlotte Family', job = 'Pirate Officer', status = 'Alive' WHERE id = 123;
UPDATE characters SET affiliation = 'Charlotte Family', job = 'Pirate Officer', status = 'Alive' WHERE id = 124;
UPDATE characters SET affiliation = 'Sun Pirates', job = 'Minister of Design (former)', status = 'Alive' WHERE id = 125;
UPDATE characters SET fruit_name = 'Memo-Memo Fruit', fruit_type = 'Paramecia', affiliation = 'Charlotte Family', job = 'Pirate Officer', status = 'Alive' WHERE id = 126;
UPDATE characters SET fruit_name = 'Wring-Wring Fruit', fruit_type = 'Paramecia', bounty = '932,000,000', affiliation = 'Charlotte Family', job = 'Sweet Commander', status = 'Alive' WHERE id = 127;
UPDATE characters SET bounty = '600,000,000', affiliation = 'Charlotte Family', job = 'Pirate Officer', status = 'Alive' WHERE id = 128;
UPDATE characters SET affiliation = 'Bliking Pirates (disbanded), Drum Kingdom (former)', job = 'Evil Chief of Staff (Chief of Staff)', status = 'Alive' WHERE id = 129;
UPDATE characters SET affiliation = 'Bliking Pirates , Drum Kingdom', job = 'Servant of Wapol', status = 'Alive' WHERE id = 130;
UPDATE characters SET bounty = '5,500,000', affiliation = 'Arlong Pirates', job = 'Pirate Officer', status = 'Alive' WHERE id = 131;
UPDATE characters SET affiliation = 'Kokoro', job = 'Sunday stationmaster of the Shift Station', status = 'Alive' WHERE id = 132;
UPDATE characters SET epithet = 'Don Chinjao', bounty = '542,000,000', affiliation = 'Chinjao Family', job = '12th Leader of the Happo Navy (retired)', status = 'Alive' WHERE id = 133;
UPDATE characters SET bounty = '500,000,000', affiliation = 'Marines', job = 'Vice Admiral', status = 'Alive' WHERE id = 136;
UPDATE characters SET affiliation = 'Mokomo Dukedom', job = 'Three Inuarashi Musketeers', status = 'Alive' WHERE id = 137;
UPDATE characters SET affiliation = 'Pumpkin Cafe', job = 'Waitress', status = 'Alive' WHERE id = 138;
UPDATE characters SET job = 'Queen dowager of the Sorbet Kingdom', status = 'Alive' WHERE id = 139;
UPDATE characters SET affiliation = 'World Government', job = 'Government official', status = 'Alive' WHERE id = 140;
UPDATE characters SET epithet = 'Blood-Splatterer Coribou', bounty = '190,000,000', affiliation = 'Caribou Pirates', job = 'Pirate', status = 'Alive' WHERE id = 141;
UPDATE characters SET affiliation = 'Germa Kingdom', job = 'Head Chef', status = 'Alive' WHERE id = 142;
UPDATE characters SET epithet = 'Sir Crocodile', fruit_name = 'Sand-Sand Fruit', fruit_type = 'Logia', bounty = '1,965,000,000', affiliation = 'Cross Guild', job = 'Pirate', status = 'Alive' WHERE id = 143;
UPDATE characters SET affiliation = 'Roger Pirates (former), Laboon', job = 'Doctor', status = 'Alive' WHERE id = 144;
UPDATE characters SET affiliation = 'Whitebeard Pirates', job = '10th Division Commander', status = 'Alive' WHERE id = 145;
UPDATE characters SET bounty = '7,800,000', affiliation = 'Dadan Family', job = 'Mountain Bandit Boss', status = 'Alive' WHERE id = 146;
UPDATE characters SET epithet = 'Daddy the Father', affiliation = 'Marines (former)', job = 'Bounty Hunter', status = 'Alive' WHERE id = 147;
UPDATE characters SET fruit_name = 'Scorpion SMILE', fruit_type = 'Artificial Zoan', affiliation = 'Beasts Pirates', job = 'Shinuchi', status = 'Alive' WHERE id = 148;
UPDATE characters SET bounty = '500,000,000', affiliation = 'Marines', job = 'Vice Admiral', status = 'Alive' WHERE id = 149;
UPDATE characters SET fruit_name = 'Ox-Ox Fruit, Bison Model', fruit_type = 'Zoan', affiliation = 'Sakura Kingdom', job = 'King of the Sakura Kingdom', status = 'Alive' WHERE id = 150;
UPDATE characters SET affiliation = 'New Fish-Man Pirates', job = 'Pirate', status = 'Alive' WHERE id = 151;
UPDATE characters SET epithet = 'The Killer', fruit_name = 'Dice-Dice Fruit', fruit_type = 'Paramecia', bounty = '75,000,000', affiliation = 'Cross Guild', job = 'Pirate', status = 'Alive' WHERE id = 152;
UPDATE characters SET affiliation = 'Subordinates of the Whitebeard Pirates', job = 'Pirates', status = 'Alive' WHERE id = 153;
UPDATE characters SET bounty = '15,000,000', affiliation = 'Donquixote Pirates', job = 'Pirate Officer', status = 'Alive' WHERE id = 154;
UPDATE characters SET epithet = 'Dozing Kyoshiro', affiliation = 'Kouzuki Family', job = 'Daimyo', status = 'Alive' WHERE id = 155;
UPDATE characters SET fruit_name = 'Ripple-Ripple Fruit', fruit_type = 'Paramecia', bounty = '99,000,000', affiliation = 'Donquixote Pirates', job = 'Pirate Executive Officer', status = 'Alive' WHERE id = 156;
UPDATE characters SET affiliation = 'Gran Tesoro', job = 'Dealer', status = 'Alive' WHERE id = 157;
UPDATE characters SET affiliation = 'Barrels Pirates', job = 'Pirate', status = 'Deceased' WHERE id = 158;
UPDATE characters SET bounty = '500,000,000', affiliation = 'Marines', job = 'Vice Admiral', status = 'Alive' WHERE id = 160;
UPDATE characters SET fruit_name = 'Hippopotamus SMILE', fruit_type = 'Artificial Zoan', affiliation = 'Beasts Pirates', job = 'Shinuchi', status = 'Alive' WHERE id = 161;
UPDATE characters SET epithet = 'Death God', fruit_name = 'Sick-Sick Fruit', fruit_type = 'Paramecia', bounty = '72,000,000', affiliation = 'Blackbeard Pirates', job = 'Titanic Captain (Captain of the Ninth Ship)', status = 'Alive' WHERE id = 162;
UPDATE characters SET affiliation = 'Dadan Family', job = 'bandit', status = 'Alive' WHERE id = 163;
UPDATE characters SET bounty = '500,000,000', affiliation = 'Marines', job = 'Vice Admiral', status = 'Alive' WHERE id = 164;
UPDATE characters SET epithet = 'Bohemian Knight', affiliation = 'Subordinate of the Whitebeard Pirates', job = 'Pirate', status = 'Alive' WHERE id = 165;
UPDATE characters SET affiliation = 'Impel Down', job = 'Head Jailer', status = 'Alive' WHERE id = 166;
UPDATE characters SET epithet = 'Heavenly Yaksha', fruit_name = 'String-String Fruit', fruit_type = 'Paramecia', bounty = '340,000,000', affiliation = 'Donquixote Pirates', job = 'Pirate Captain', status = 'Alive' WHERE id = 167;
UPDATE characters SET fruit_name = 'Calm-Calm Fruit', fruit_type = 'Paramecia', affiliation = 'Marines', job = 'Marine Commander', status = 'Deceased' WHERE id = 168;
UPDATE characters SET affiliation = 'New Fish-Man Pirates', job = 'Pirate', status = 'Alive' WHERE id = 169;
UPDATE characters SET epithet = 'Demon Heir', fruit_name = 'Clank-Clank Fruit', fruit_type = 'Paramecia', affiliation = 'Roger Pirates (former)', job = 'Pirate', status = 'Alive' WHERE id = 170;
UPDATE characters SET epithet = 'Hawk Eyes Mihawk', bounty = '3,590,000,000', affiliation = 'Cross Guild', job = 'Pirate', status = 'Alive' WHERE id = 172;
UPDATE characters SET job = 'Guard', status = 'Deceased' WHERE id = 173;
UPDATE characters SET epithet = 'Iron Mask Duval', affiliation = 'Rosy Life Riders', job = 'Leader of the Rosy Life Riders (formerly the Flying Fish Riders)', status = 'Alive' WHERE id = 174;
UPDATE characters SET affiliation = 'Marines ( SSG ) (former)', status = 'Alive' WHERE id = 175;
UPDATE characters SET epithet = 'Whitebeard', fruit_name = 'Tremor-Tremor Fruit', fruit_type = 'Paramecia', bounty = '5,046,000,000', affiliation = 'Whitebeard Pirates', job = 'Pirate Captain', status = 'Deceased' WHERE id = 176;
UPDATE characters SET bounty = '480,000,000', affiliation = 'Seven Warlords of the Sea (former)', job = 'Pirate', status = 'Alive' WHERE id = 177;
UPDATE characters SET fruit_name = 'Pop-Pop Fruit', fruit_type = 'Paramecia', bounty = '31,000,000', affiliation = 'Donquixote Pirates', job = 'Pirate Officer', status = 'Alive' WHERE id = 222;
UPDATE characters SET affiliation = 'Kuja', job = 'Empress of Amazon Lily (former)', status = 'Alive' WHERE id = 223;
UPDATE characters SET epithet = 'Pirate King', bounty = '5,564,800,000', affiliation = 'Roger Pirates', job = 'Pirate Captain', status = 'Deceased' WHERE id = 224;
UPDATE characters SET affiliation = 'Chimney', job = 'Pet', status = 'Alive' WHERE id = 225;
UPDATE characters SET affiliation = 'Poseidon', status = 'Alive' WHERE id = 226;
UPDATE characters SET job = 'King (former)', status = 'Alive' WHERE id = 227;
UPDATE characters SET affiliation = 'Kuja Pirates', job = 'Pirates' WHERE id = 228;
UPDATE characters SET affiliation = 'Ukkari Hot-Spring Island', job = 'Onsen manager', status = 'Alive' WHERE id = 229;
UPDATE characters SET bounty = '90,000,000', affiliation = 'Fire Tank Pirates', job = 'Pirate , Assassin , Combatant', status = 'Alive' WHERE id = 230;
UPDATE characters SET affiliation = 'CP0', job = 'Cipher Pol Agent', status = 'Deceased' WHERE id = 231;
UPDATE characters SET affiliation = 'Bonney Pirates', job = 'Fishmonger (former)', status = 'Alive' WHERE id = 232;
UPDATE characters SET epithet = 'Crab-Hand Gyro', bounty = '73,000,000', affiliation = 'Gyro Pirates , New Fish-Man Pirates (ruse, former)', job = 'Pirate', status = 'Alive' WHERE id = 233;
UPDATE characters SET epithet = 'Hundredth Dan Hack', affiliation = 'Revolutionary Army', job = 'Revolutionary Army member', status = 'Alive' WHERE id = 234;
UPDATE characters SET affiliation = 'New Giant Warrior Pirates', job = 'Captain of the Sixth Ship of the Straw Hat Grand Fleet', status = 'Alive' WHERE id = 235;
UPDATE characters SET epithet = 'Four-Footed Dash Freak', affiliation = 'Foxy Pirates', job = 'Pirate', status = 'Alive' WHERE id = 236;
UPDATE characters SET fruit_name = 'Giraffe SMILE', fruit_type = 'Artificial Zoan', affiliation = 'Beasts Pirates', job = 'Shinuchi', status = 'Alive' WHERE id = 237;
UPDATE characters SET affiliation = 'New Fish-Man Pirates', job = 'Pirate', status = 'Alive' WHERE id = 238;
UPDATE characters SET affiliation = 'Robecca Hanberg', job = 'Salesperson', status = 'Alive' WHERE id = 239;
UPDATE characters SET affiliation = 'Impel Down', job = 'Chief Warden', status = 'Alive' WHERE id = 240;
UPDATE characters SET job = 'Scientist', status = 'Alive' WHERE id = 241;
UPDATE characters SET affiliation = 'Whitebeard Pirates', job = '12th Division Commander', status = 'Alive' WHERE id = 242;
UPDATE characters SET affiliation = 'Ukkari Hot-Spring Island', job = 'Ukkari Hot-Springs Resort Transportation', status = 'Alive' WHERE id = 243;
UPDATE characters SET affiliation = 'Beasts Pirates ( Numbers )', status = 'Alive' WHERE id = 244;
UPDATE characters SET epithet = 'Six Sword Style Hachi', bounty = '8,000,000', affiliation = 'Takoyaki 8', job = 'Takoyaki seller', status = 'Alive' WHERE id = 245;
UPDATE characters SET affiliation = 'CP0', job = 'Rob Lucci ''s Pet', status = 'Alive' WHERE id = 246;
UPDATE characters SET affiliation = 'Kid Pirates', job = 'Pirate', status = 'Unknown' WHERE id = 247;
UPDATE characters SET bounty = '100,000,000', affiliation = 'Marines ( Headquarters', job = 'Lieutenant Commander', status = 'Alive' WHERE id = 248;
UPDATE characters SET epithet = 'Hera the Thundercloud', affiliation = 'Big Mom Pirates', job = 'Living Weapon', status = 'Unknown' WHERE id = 249;
UPDATE characters SET job = 'Explorer', status = 'Alive' WHERE id = 250;
UPDATE characters SET bounty = '200,000,000', affiliation = 'Marines', job = 'Commander', status = 'Alive' WHERE id = 251;
UPDATE characters SET bounty = '8,000,000', affiliation = 'Higuma Bandits', job = 'Bandit Leader', status = 'Deceased' WHERE id = 252;
UPDATE characters SET affiliation = 'Thriller Bark Pirates', job = 'Wild Zombie', status = 'Deceased' WHERE id = 253;
UPDATE characters SET epithet = 'Black Cage Hina', fruit_name = 'Bind-Bind Fruit', fruit_type = 'Paramecia', bounty = '200,000,000', affiliation = 'Marines (Black Cage Corps)', job = 'Rear Admiral', status = 'Alive' WHERE id = 254;
UPDATE characters SET job = 'Doctor', status = 'Deceased' WHERE id = 255;
UPDATE characters SET affiliation = 'New Fish-Man Pirates', job = 'Pirate', status = 'Alive' WHERE id = 256;
UPDATE characters SET epithet = 'Doctor Hogback', affiliation = 'Thriller Bark Pirates (Mysterious Four)', job = 'Doctor', status = 'Alive' WHERE id = 257;
UPDATE characters SET affiliation = 'God''s Army', job = 'Pet', status = 'Alive' WHERE id = 259;
UPDATE characters SET affiliation = 'Red Hair Pirates', job = 'Pirate', status = 'Alive' WHERE id = 260;
UPDATE characters SET affiliation = 'God''s Army', job = 'Lieutenants of the Divine Soldiers', status = 'Unknown' WHERE id = 261;
UPDATE characters SET epithet = 'Hyougoro of the Flower', affiliation = 'Hyougoro Family (former)', job = 'Prisoner (former)', status = 'Alive' WHERE id = 262;
UPDATE characters SET affiliation = 'New Fish-Man Pirates', job = 'Mercenary', status = 'Alive' WHERE id = 263;
UPDATE characters SET affiliation = 'Galley-La Company', job = 'President of the Galley-La Company', status = 'Alive' WHERE id = 265;
UPDATE characters SET epithet = 'Destruction Cannon', affiliation = 'Ideo Pirates', job = 'Captain of the Fourth Ship of the Straw Hat Grand Fleet', status = 'Alive' WHERE id = 266;
UPDATE characters SET affiliation = 'Arabasta', job = 'Captain of the Royal Guard', status = 'Alive' WHERE id = 267;
UPDATE characters SET affiliation = 'New Fish-Man Pirates', job = 'Pirate', status = 'Alive' WHERE id = 268;
UPDATE characters SET fruit_name = 'The Devil''s Fruit', affiliation = 'World Government ( Nerona Family )', job = 'King of the World (clandestine)', status = 'Alive' WHERE id = 269;
UPDATE characters SET fruit_name = 'Snip-Snip Fruit', fruit_type = 'Paramecia', bounty = '100,000,000', affiliation = 'Kamabakka Kingdom', job = 'Revolutionary', status = 'Alive' WHERE id = 270;
UPDATE characters SET affiliation = 'Golden Lion Pirates', job = 'Pirate', status = 'Alive' WHERE id = 271;
UPDATE characters SET epithet = 'Duke Inuarashi', affiliation = 'Mokomo Dukedom', job = 'Daimyo', status = 'Alive' WHERE id = 272;
UPDATE characters SET affiliation = 'Thriller Bark', job = 'Wild Zombie', status = 'Deceased' WHERE id = 273;
UPDATE characters SET affiliation = 'Loguetown Arms Shop', job = 'Arms Shop Proprietor', status = 'Alive' WHERE id = 274;
UPDATE characters SET affiliation = 'Mermaid Cafe Dancers', job = 'Dancer', status = 'Alive' WHERE id = 275;
UPDATE characters SET fruit_name = 'Press-Press Fruit', fruit_type = 'Paramecia', bounty = '3,000,000,000', affiliation = 'Marines', job = 'Admiral', status = 'Alive' WHERE id = 276;
UPDATE characters SET epithet = 'Nailing', bounty = '1,000,000', job = 'Marine Ensign', status = 'Alive' WHERE id = 277;
UPDATE characters SET affiliation = 'Foxy Pirates (former)', job = 'Pirate', status = 'Alive' WHERE id = 278;
UPDATE characters SET bounty = '510,000,000', affiliation = 'Whitebeard Pirates (former)', job = '16th Division Commander (former)', status = 'Deceased' WHERE id = 279;
UPDATE characters SET fruit_name = 'Mutt-Mutt Fruit Wolf Model', fruit_type = 'Zoan', affiliation = 'CP0', job = 'Cipher Pol Agent', status = 'Alive' WHERE id = 280;
UPDATE characters SET epithet = 'Jack the Drought', fruit_name = 'Elephant-Elephant Fruit, Ancient Zoan Model: Mammoth', fruit_type = 'Ancient Zoan', bounty = '1,000,000,000', affiliation = 'Beasts Pirates', job = 'All-Star', status = 'Alive' WHERE id = 281;
UPDATE characters SET affiliation = 'Walrus School', job = 'History Teacher', status = 'Alive' WHERE id = 282;
UPDATE characters SET affiliation = 'World Government', job = 'World Noble', status = 'Alive' WHERE id = 283;
UPDATE characters SET epithet = 'One-Two Jango', bounty = '1,000,000', affiliation = 'Marines', job = 'Marine Lieutenant Commander', status = 'Alive' WHERE id = 284;
UPDATE characters SET affiliation = 'Five Elders', job = 'Co-Head of the World Government (Public)', status = 'Deceased' WHERE id = 285;
UPDATE characters SET affiliation = 'Heart Pirates', job = 'Pirate', status = 'Unknown' WHERE id = 286;
UPDATE characters SET affiliation = 'CP6', job = 'Cipher Pol Agent', status = 'Alive' WHERE id = 288;
UPDATE characters SET epithet = 'Champion', fruit_name = 'Strong-Strong Fruit', fruit_type = 'Paramecia', bounty = '20,000,000', affiliation = 'Blackbeard Pirates', job = 'Titanic Captain (Captain of the First Ship)', status = 'Alive' WHERE id = 289;
UPDATE characters SET epithet = 'Big Eater', fruit_name = 'Age-Age Fruit', fruit_type = 'Paramecia', bounty = '320,000,000', affiliation = 'Bonney Pirates', job = 'Pirate Captain', status = 'Alive' WHERE id = 290;
UPDATE characters SET epithet = 'Knight of the Sea Jinbe', bounty = '1,100,000,000', affiliation = 'Straw Hat Pirates', job = 'Pirate', status = 'Alive' WHERE id = 292;
UPDATE characters SET epithet = 'Captain John', fruit_name = 'Magnet-Magnet Fruit', fruit_type = 'Paramecia', affiliation = 'Rocks Pirates (former)', job = 'General Zombie', status = 'Deceased' WHERE id = 293;
UPDATE characters SET bounty = '500,000,000', affiliation = 'Marines', job = 'Vice Admiral', status = 'Alive' WHERE id = 294;
UPDATE characters SET affiliation = 'Yosaku', job = 'Bounty Hunter (former)', status = 'Alive' WHERE id = 295;
UPDATE characters SET affiliation = 'Marines', job = 'Vice Admiral', status = 'Alive' WHERE id = 296;
UPDATE characters SET affiliation = 'CP0', job = 'Cipher Pol Agent', status = 'Alive' WHERE id = 297;
UPDATE characters SET epithet = 'Diamond Jozu', fruit_name = 'Twinkle-Twinkle Fruit', fruit_type = 'Paramecia', affiliation = 'Whitebeard Pirates', job = 'Pirate', status = 'Alive' WHERE id = 298;
UPDATE characters SET fruit_name = 'Bug-Bug Fruit, Model: Rhinoceros beetle', fruit_type = 'Zoan', affiliation = 'Tontatta Kingdom', job = 'Leader of Yellow Kabu Squad', status = 'Alive' WHERE id = 299;
UPDATE characters SET epithet = 'Kaidou of the Beasts', fruit_name = 'Fish-Fish Fruit, Model: Azure Dragon', fruit_type = 'Mythical Zoan', bounty = '4,611,100,000', affiliation = 'Beasts Pirates', job = 'Governor-General', status = 'Unknown' WHERE id = 300;
UPDATE characters SET epithet = 'Kaidou of the Beasts', fruit_name = 'Fish-Fish Fruit, Model: Azure Dragon', fruit_type = 'Mythical Zoan', bounty = '4,611,100,000', affiliation = 'Beasts Pirates', job = 'Governor-General', status = 'Unknown' WHERE id = 301;
UPDATE characters SET epithet = 'Mountain Wind', fruit_name = 'Ox-Ox Fruit Giraffe Model', fruit_type = 'Zoan', affiliation = 'CP0', job = 'Cipher Pol Agent', status = 'Alive' WHERE id = 302;
UPDATE characters SET epithet = 'The Demon of Shandora', affiliation = 'Shandia', job = 'Warrior', status = 'Deceased' WHERE id = 303;
UPDATE characters SET fruit_name = 'Bubble-Bubble Fruit', fruit_type = 'Paramecia', affiliation = 'CP0', job = 'Cipher Pol Agent', status = 'Alive' WHERE id = 304;
UPDATE characters SET affiliation = 'Shandia', job = 'Shandia Warrior', status = 'Alive' WHERE id = 305;
UPDATE characters SET fruit_name = 'Soot-Soot Fruit', fruit_type = 'Logia', bounty = '400,000,000', affiliation = 'Revolutionary Army (North Army)', job = 'North Army Commander of the Revolutionary Army', status = 'Alive' WHERE id = 306;
UPDATE characters SET affiliation = 'Arabasta Kingdom Guard Squad ( Super Spot-Billed Duck Troops ), Straw Hat Pirates (former), Baroque Works (former)', job = 'Pet', status = 'Alive' WHERE id = 307;
UPDATE characters SET affiliation = 'World Government (defected ), Giant Warrior Pirates', job = 'Pirate , Gate Guardian (former )', status = 'Alive' WHERE id = 308;
UPDATE characters SET epithet = 'Kawamatsu the Kappa', affiliation = 'Kouzuki Family', job = 'Daimyo', status = 'Alive' WHERE id = 309;
UPDATE characters SET job = 'Medical student', status = 'Alive' WHERE id = 310;
UPDATE characters SET fruit_name = 'Jacket-Jacket Fruit', fruit_type = 'Paramecia', bounty = '57,000,000', affiliation = 'Mogaro Kingdom', job = 'Assassin', status = 'Alive' WHERE id = 311;
UPDATE characters SET epithet = 'Kikunojo of the Lingering Snow', affiliation = 'Kouzuki Family', job = 'Daimyo of Ringo', status = 'Alive' WHERE id = 312;
UPDATE characters SET epithet = 'Massacre Soldier', bounty = '200,000,000', affiliation = 'Kid Pirates', job = 'Pirate', status = 'Unknown' WHERE id = 313;
UPDATE characters SET epithet = 'Foxfire Kin''emon', fruit_name = 'Garb-Garb Jutsu', fruit_type = 'Paramecia', affiliation = 'Kouzuki Family', job = 'Samurai', status = 'Alive' WHERE id = 314;
UPDATE characters SET epithet = 'King the Conflagration', fruit_name = 'Dragon-Dragon Fruit, Model: Pteranodon', fruit_type = 'Ancient Zoan', bounty = '1,390,000,000', affiliation = 'Beasts Pirates', job = 'All-Star', status = 'Alive' WHERE id = 315;
UPDATE characters SET affiliation = 'Big Mom Pirates', job = 'Master of the Seducing Woods', status = 'Unknown' WHERE id = 316;
UPDATE characters SET affiliation = 'Whitebeard Pirates', job = '11th Division Commander', status = 'Alive' WHERE id = 317;
UPDATE characters SET affiliation = 'Revolutionary Army', job = 'Revolutionary Army Officer', status = 'Alive' WHERE id = 319;
UPDATE characters SET epithet = 'Hero', bounty = '500,000,000', affiliation = 'Marines ( SWORD ), Marine 153rd Branch (former)', job = 'Marine Captain', status = 'Alive' WHERE id = 320;
UPDATE characters SET affiliation = 'Tom''s Workers', job = 'Stationmaster', status = 'Alive' WHERE id = 321;
UPDATE characters SET affiliation = 'Kurozumi Tama', status = 'Alive' WHERE id = 322;
UPDATE characters SET epithet = 'Genius Tactician', affiliation = 'Marines', job = 'Vice Admiral', status = 'Alive' WHERE id = 323;
UPDATE characters SET affiliation = 'God''s Army', job = 'Lieutenants of the Divine Soldiers', status = 'Unknown' WHERE id = 324;
UPDATE characters SET affiliation = 'Shimotsuki Family', job = 'Dojo Master', status = 'Alive' WHERE id = 325;
UPDATE characters SET fruit_name = 'Time-Time Ability', fruit_type = 'Paramecia', affiliation = 'Kouzuki Family', status = 'Deceased' WHERE id = 326;
UPDATE characters SET affiliation = 'Arabasta Kingdom', job = 'Environmental Minister', status = 'Alive' WHERE id = 327;
UPDATE characters SET affiliation = 'Kouzuki Family', job = 'Oiran', status = 'Alive' WHERE id = 328;
UPDATE characters SET fruit_name = 'Fish-Fish Fruit, Model: Azure Dragon', fruit_type = 'Mythical Zoan', affiliation = 'Kouzuki Family', job = 'Shogun', status = 'Alive' WHERE id = 329;
UPDATE characters SET epithet = 'Idiot Lord', affiliation = 'Kouzuki Family', job = 'Samurai', status = 'Deceased' WHERE id = 330;
UPDATE characters SET affiliation = 'Kouzuki Family', job = 'Swordsmith', status = 'Alive' WHERE id = 331;
UPDATE characters SET fruit_name = 'Time-Time Ability', fruit_type = 'Paramecia', affiliation = 'Kouzuki Family', status = 'Deceased' WHERE id = 332;
UPDATE characters SET epithet = 'Don Krieg', bounty = '17,000,000', affiliation = 'Krieg Pirates', job = 'Pirate Captain / Admiral', status = 'Alive' WHERE id = 333;
UPDATE characters SET affiliation = 'Shimotsuki Family', job = 'Trainee Swordsman', status = 'Deceased' WHERE id = 334;
UPDATE characters SET fruit_name = 'Whip-Whip Fruit', fruit_type = 'Paramecia', bounty = '500,000,000', affiliation = 'Marines ( G-14 )', job = 'Rear Admiral', status = 'Alive' WHERE id = 335;
UPDATE characters SET affiliation = 'CP0', job = 'Cipher Pol Agent', status = 'Alive' WHERE id = 336;
UPDATE characters SET affiliation = 'Thriller Bark Pirates ( Perona )', job = 'Perona''s servant', status = 'Deceased' WHERE id = 337;
UPDATE characters SET epithet = 'Witch', affiliation = 'Sakura Kingdom', job = 'Head- Doctor of the Sakura Kingdom', status = 'Alive' WHERE id = 338;
UPDATE characters SET epithet = 'Kuro of a Hundred Plans', bounty = '16,000,000', affiliation = 'Black Cat Pirates', job = 'Pirate Captain (former)', status = 'Alive' WHERE id = 339;
UPDATE characters SET affiliation = 'Bliking Pirates (disbanded), Drum Kingdom (former)', job = 'Evil Magistrate (Magistrate)', status = 'Alive' WHERE id = 340;
UPDATE characters SET bounty = '9,000,000', affiliation = 'Arlong Pirates', job = 'Pirate Officer', status = 'Alive' WHERE id = 341;
UPDATE characters SET fruit_name = 'Clone-Clone Fruit', fruit_type = 'Paramecia', affiliation = 'Wano Country ( Kurozumi Family )', status = 'Deceased' WHERE id = 342;
UPDATE characters SET epithet = 'Evening Shower', fruit_name = 'Brush-Brush Fruit', fruit_type = 'Paramecia', affiliation = 'Kurozumi Family', job = 'Theatre Performer (former)', status = 'Deceased' WHERE id = 343;
UPDATE characters SET fruit_name = 'Snake-Snake Fruit, Model: Eight Headed Serpent', fruit_type = 'Mythical Zoan', affiliation = 'Wano Country ( Kurozumi Family )', job = 'Shogun of Wano Country (former)', status = 'Deceased' WHERE id = 344;
UPDATE characters SET fruit_name = 'Barrier-Barrier Fruit', fruit_type = 'Paramecia', affiliation = 'Wano Country ( Kurozumi Family )', job = 'Biwa hōshi', status = 'Deceased' WHERE id = 345;
UPDATE characters SET fruit_name = 'Millet-Millet Fruit', fruit_type = 'Paramecia', affiliation = 'Kurozumi Family', job = 'Kunoichi in training', status = 'Alive' WHERE id = 346;
UPDATE characters SET fruit_name = 'Ice-Ice Fruit', fruit_type = 'Logia', affiliation = 'Blackbeard Pirates', job = 'Titanic Captain (Captain of the Tenth Ship)', status = 'Alive' WHERE id = 347;
UPDATE characters SET affiliation = 'Corrida Colosseum (former)', job = 'Gladiator (former)', status = 'Alive' WHERE id = 349;
UPDATE characters SET affiliation = 'Donquixote Pirates (former)', job = 'Pirate', status = 'Alive' WHERE id = 350;
UPDATE characters SET affiliation = 'Rumbar Pirates (former)', status = 'Alive' WHERE id = 351;
UPDATE characters SET epithet = 'Demon Sheriff', bounty = '42,200,000', affiliation = 'Blackbeard Pirates', job = 'Titanic Captain (Captain of the Fifth Ship)', status = 'Alive' WHERE id = 352;
UPDATE characters SET bounty = '61,000,000', affiliation = 'Donquixote Pirates', job = 'Pirate Officer', status = 'Alive' WHERE id = 353;
UPDATE characters SET epithet = 'Warrior', fruit_name = 'Stitch-Stitch Power', fruit_type = 'Paramecia', affiliation = 'Tontatta Kingdom', job = 'Captain of the Fifth Ship of the Straw Hat Grand Fleet', status = 'Alive' WHERE id = 355;
UPDATE characters SET affiliation = 'Marines ( SSG ) (former)', status = 'Alive' WHERE id = 357;
UPDATE characters SET affiliation = 'Red Arrows Pirates', status = 'Deceased' WHERE id = 358;
UPDATE characters SET affiliation = 'Wandering Clan', job = 'Sky Priestess', status = 'Alive' WHERE id = 359;
UPDATE characters SET affiliation = 'Red Hair Pirates', job = 'Pirate', status = 'Alive' WHERE id = 360;
UPDATE characters SET bounty = '316,000,000', affiliation = 'Revolutionary Army (South Army)', job = 'South Army Commander of the Revolutionary Army', status = 'Alive' WHERE id = 361;
UPDATE characters SET job = 'Foosha Village ''s local Sea King', status = 'Alive' WHERE id = 364;
UPDATE characters SET affiliation = 'Red Hair Pirates', job = 'Pirate', status = 'Alive' WHERE id = 365;
UPDATE characters SET fruit_name = 'Ton-Ton Fruit', fruit_type = 'Paramecia', bounty = '11,000,000', affiliation = 'Donquixote Pirates', job = 'Pirate Officer', status = 'Alive' WHERE id = 366;
UPDATE characters SET fruit_name = 'Chain-Chain Fruit', fruit_type = 'Paramecia', affiliation = 'Treasure Pirates', job = 'Treasure Hunter , Pirate', status = 'Alive' WHERE id = 367;
UPDATE characters SET fruit_name = 'Venom-Venom Fruit', fruit_type = 'Paramecia', affiliation = 'Impel Down', job = 'Vice Warden', status = 'Alive' WHERE id = 368;
UPDATE characters SET affiliation = 'Dadan Family', job = 'Bandit', status = 'Alive' WHERE id = 369;
UPDATE characters SET affiliation = 'CP0', job = 'Cipher Pol Agent', status = 'Unknown' WHERE id = 370;
UPDATE characters SET affiliation = 'Partys Bar', job = 'Bar Owner', status = 'Alive' WHERE id = 371;
UPDATE characters SET affiliation = 'Neptune Family', job = 'Prince of the Ryugu Kingdom', status = 'Alive' WHERE id = 372;
UPDATE characters SET fruit_name = 'Heal-Heal Fruit', fruit_type = 'Paramecia', affiliation = 'Tontatta Kingdom', job = 'Princess', status = 'Alive' WHERE id = 373;
UPDATE characters SET epithet = 'Marco the Phoenix', fruit_name = 'Tweet-Tweet Fruit, Phoenix Model', fruit_type = 'Mythical Zoan', bounty = '1,374,000,000', affiliation = 'Whitebeard Pirates (former)', job = 'Doctor', status = 'Alive' WHERE id = 374;
UPDATE characters SET affiliation = 'Five Elders', job = 'Co-Head of the World Government (Public)', status = 'Alive' WHERE id = 375;
UPDATE characters SET affiliation = 'Egana', job = 'Maid', status = 'Alive' WHERE id = 376;
UPDATE characters SET affiliation = 'Kuja Pirates', job = 'Pirate', status = 'Alive' WHERE id = 377;
UPDATE characters SET affiliation = 'Spade Pirates', job = 'Journalist', status = 'Alive' WHERE id = 378;
UPDATE characters SET epithet = 'Maynard the Pursuer', bounty = '500,000,000', affiliation = 'Marines', job = 'Vice Admiral', status = 'Alive' WHERE id = 379;
UPDATE characters SET epithet = 'Thunder Lord', affiliation = 'Subordinate of the Whitebeard Pirates', job = 'Pirate', status = 'Alive' WHERE id = 380;
UPDATE characters SET affiliation = 'Ryugu Kingdom', job = 'Shirahoshi ''s pet', status = 'Alive' WHERE id = 381;
UPDATE characters SET affiliation = 'Kaya', job = 'Butler', status = 'Alive' WHERE id = 382;
UPDATE characters SET affiliation = 'Mokomo Dukedom', job = 'Guardian', status = 'Alive' WHERE id = 383;
UPDATE characters SET affiliation = 'Impel Down', job = 'Jailer Beast', status = 'Alive' WHERE id = 384;
UPDATE characters SET affiliation = 'Impel Down', job = 'Jailer Beast', status = 'Alive' WHERE id = 385;
UPDATE characters SET affiliation = 'Impel Down', job = 'Jailer Beast', status = 'Alive' WHERE id = 386;
UPDATE characters SET affiliation = 'Impel Down', job = 'Jailer Beast', status = 'Alive' WHERE id = 387;
UPDATE characters SET affiliation = 'Impel Down', job = 'Jailer Beast', status = 'Alive' WHERE id = 388;
UPDATE characters SET epithet = 'Poison Spider Zala', fruit_name = 'Spike-Spike Fruit', fruit_type = 'Paramecia', bounty = '35,000,000', affiliation = 'New Spiders Cafe', job = 'Spiders Cafe Owner', status = 'Alive' WHERE id = 389;
UPDATE characters SET affiliation = 'Baroque Works (former)', job = 'Assassin (former)', status = 'Alive' WHERE id = 390;
UPDATE characters SET epithet = 'Flag-Bearer of Freedom', bounty = '29,000,000', affiliation = 'New Spiders Cafe', job = 'Cafe Employee', status = 'Alive' WHERE id = 391;
UPDATE characters SET epithet = 'Town-Collapser Drophy', fruit_name = 'Mole-Mole Fruit', fruit_type = 'Zoan', bounty = '14,000,000', affiliation = 'New Spiders Cafe', job = 'Cafe Waitress', status = 'Alive' WHERE id = 392;
UPDATE characters SET affiliation = 'Baroque Works (former)', job = 'Frontier Agent (former)', status = 'Alive' WHERE id = 393;
UPDATE characters SET epithet = 'Courier', fruit_name = 'Kilo-Kilo Fruit', fruit_type = 'Paramecia', bounty = '7,500,000', affiliation = 'New Spiders Cafe', job = 'Cafe Pâtissier', status = 'Alive' WHERE id = 396;
UPDATE characters SET affiliation = 'Mokomo Dukedom', job = 'Doctor', status = 'Alive' WHERE id = 397;
UPDATE characters SET fruit_name = 'Gorilla SMILE', fruit_type = 'Artificial Zoan', affiliation = 'Beasts Pirates', job = 'Shinuchi', status = 'Alive' WHERE id = 398;
UPDATE characters SET status = 'Alive' WHERE id = 399;
UPDATE characters SET affiliation = 'Revolutionary Army', job = 'Farmer', status = 'Alive' WHERE id = 400;
UPDATE characters SET epithet = 'Beast Tamer', affiliation = 'Cross Guild', job = 'Pirate', status = 'Alive' WHERE id = 401;
UPDATE characters SET bounty = '500,000,000', affiliation = 'Marines G-1 Branch', job = 'Vice Admiral', status = 'Alive' WHERE id = 402;
UPDATE characters SET epithet = 'Momoo the Sea Cow', affiliation = 'Arlong Pirates (former)', job = 'Arlong Pirates'' pet (former)', status = 'Alive' WHERE id = 403;
UPDATE characters SET affiliation = 'Foxy Pirates (former)', job = 'Pet', status = 'Alive' WHERE id = 404;
UPDATE characters SET fruit_name = 'Snow-Snow Fruit', fruit_type = 'Logia', affiliation = 'Caesar Clown (espionage)', job = 'Caesar''s secretary (Undercover)', status = 'Deceased' WHERE id = 405;
UPDATE characters SET epithet = 'Rebellious Dragon', affiliation = 'Revolutionary Army', job = 'Supreme Commander of the Revolutionary Army', status = 'Alive' WHERE id = 406;
UPDATE characters SET epithet = 'Garp the Fist', bounty = '3,000,000,000', affiliation = 'Marines (semi-retired)', job = 'Vice Admiral', status = 'Alive' WHERE id = 407;
UPDATE characters SET epithet = 'Straw Hat Luffy', fruit_name = 'Gum-Gum Fruit', fruit_type = 'Paramecia', bounty = '3,000,000,000', affiliation = 'Straw Hat Pirates', job = 'Pirate Captain', status = 'Alive' WHERE id = 408;
UPDATE characters SET affiliation = 'Red Hair Pirates', job = 'Pirate', status = 'Alive' WHERE id = 409;
UPDATE characters SET bounty = '25,000,000', affiliation = 'Saruyama Alliance', job = 'Pirate', status = 'Alive' WHERE id = 410;
UPDATE characters SET epithet = 'Liar Noland', affiliation = 'Lvneel Kingdom', job = 'Explorer', status = 'Deceased' WHERE id = 411;
UPDATE characters SET epithet = 'Axe-Hand Morgan', affiliation = 'Marines ( 153rd Branch ) (former, defected)', job = 'Marine Captain (former)', status = 'Alive' WHERE id = 412;
UPDATE characters SET epithet = 'Big News', fruit_name = 'Tweet-Tweet Fruit, Albatross Model', fruit_type = 'Zoan', affiliation = 'World Economy News Paper', job = 'World Economy News Paper President', status = 'Alive' WHERE id = 413;
UPDATE characters SET epithet = 'Morley of Fur', fruit_name = 'Push-Push Fruit', fruit_type = 'Paramecia', bounty = '293,000,000', affiliation = 'Revolutionary Army (West Army)', job = 'West Army Commander of the Revolutionary Army', status = 'Alive' WHERE id = 414;
UPDATE characters SET affiliation = 'Poseidon', status = 'Alive' WHERE id = 415;
UPDATE characters SET affiliation = 'Kouzuki Family', job = 'Retainer', status = 'Unknown' WHERE id = 416;
UPDATE characters SET bounty = '500,000,000', affiliation = 'Marines', job = 'Vice Admiral', status = 'Alive' WHERE id = 417;
UPDATE characters SET epithet = 'Square Sisters', affiliation = 'Franky Family (former)', job = 'Bartenders', status = 'Alive' WHERE id = 418;
UPDATE characters SET affiliation = 'Baroque Works (former)', job = 'Assassin (former)', status = 'Alive' WHERE id = 419;
UPDATE characters SET epithet = 'Catcher-Killing Babe', bounty = '3,200,000', affiliation = 'New Spiders Cafe', job = 'Cafe Delivery Boy', status = 'Alive' WHERE id = 420;
UPDATE characters SET epithet = 'Gem of the Border', fruit_name = 'Bomb-Bomb Fruit', fruit_type = 'Paramecia', bounty = '10,000,000', affiliation = 'New Spiders Cafe', job = 'Cafe Employee', status = 'Alive' WHERE id = 421;
UPDATE characters SET affiliation = 'Baroque Works (former)', job = 'Frontier Agent (former)', status = 'Alive' WHERE id = 422;
UPDATE characters SET fruit_name = 'Shroom-Shroom Fruit', fruit_type = 'Paramecia', affiliation = 'Bliking Pirates (disbanded)', job = 'Pirate', status = 'Alive' WHERE id = 423;
UPDATE characters SET affiliation = 'Legendary Alchemi Research Lab', status = 'Alive' WHERE id = 424;
UPDATE characters SET epithet = 'Cat Burglar', bounty = '366,000,000', affiliation = 'Straw Hat Pirates', job = 'Navigator', status = 'Alive' WHERE id = 426;
UPDATE characters SET affiliation = 'Whitebeard Pirates', job = '8th Division Commander', status = 'Alive' WHERE id = 427;
UPDATE characters SET epithet = 'Napoleon the Bicorne', affiliation = 'Big Mom Pirates', status = 'Unknown' WHERE id = 428;
UPDATE characters SET affiliation = 'Arabasta Kingdom', job = 'King of Arabasta', status = 'Deceased' WHERE id = 429;
UPDATE characters SET affiliation = 'Arabasta Kingdom ( Nefertari Family )', job = 'Princess of Arabasta', status = 'Alive' WHERE id = 430;
UPDATE characters SET job = 'Housewife', status = 'Alive' WHERE id = 431;
UPDATE characters SET epithet = 'Master Nekomamushi', affiliation = 'Mokomo Dukedom', job = 'Yakuza Boss', status = 'Alive' WHERE id = 432;
UPDATE characters SET epithet = 'God of the Sea', affiliation = 'Neptune Family', job = 'King of the Ryugu Kingdom', status = 'Alive' WHERE id = 433;
UPDATE characters SET epithet = 'Nero the Sea Weasel', affiliation = 'CP9 (former)', job = 'Cipher Pol Agent (former)', status = 'Unknown' WHERE id = 434;
UPDATE characters SET bounty = '100,000,000', affiliation = 'Marines', job = 'Marine Captain', status = 'Alive' WHERE id = 435;
UPDATE characters SET bounty = '79,000,000', affiliation = 'Ohara Archaeologists', job = 'Archaeologist', status = 'Deceased' WHERE id = 436;
UPDATE characters SET epithet = 'Devil Child', fruit_name = 'Hana-Hana Fruit', fruit_type = 'Paramecia', bounty = '930,000,000', affiliation = 'Straw Hat Pirates', job = 'Archaeologist', status = 'Alive' WHERE id = 437;
UPDATE characters SET affiliation = 'Big Mom Pirates', status = 'Alive' WHERE id = 438;
UPDATE characters SET affiliation = 'Bell-mère''s mikan', job = 'Mikan Farmer', status = 'Alive' WHERE id = 439;
UPDATE characters SET epithet = 'Master of the Sky', affiliation = 'Shandia', status = 'Alive' WHERE id = 440;
UPDATE characters SET epithet = 'Devil', affiliation = 'Thriller Bark Pirates', job = 'Special Zombie', status = 'Deceased' WHERE id = 441;
UPDATE characters SET epithet = 'Skybreeder', affiliation = 'God''s Army (former)', job = 'Priest of Enel (former)', status = 'Unknown' WHERE id = 443;
UPDATE characters SET affiliation = 'World Government (defected )', job = 'Pirate', status = 'Alive' WHERE id = 444;
UPDATE characters SET epithet = 'Baron Omatsuri', affiliation = 'Red Arrows Pirates', job = 'Resort Owner, Pirate , Captain', status = 'Deceased' WHERE id = 447;
UPDATE characters SET bounty = '500,000,000', affiliation = 'Marines', job = 'Vice Admiral', status = 'Alive' WHERE id = 449;
UPDATE characters SET epithet = 'Gyukimaru on Oihagi Bridge', fruit_type = 'Mythical Zoan', affiliation = 'Shimotsuki Family ( Shimotsuki Ushimaru )', job = 'Warrior Monk', status = 'Alive' WHERE id = 450;
UPDATE characters SET epithet = 'Massacre Ruler', bounty = '148,000,000', affiliation = 'Yonta Maria Grand Fleet', job = 'Captain of the Seventh Ship of the Straw Hat Grand Fleet', status = 'Alive' WHERE id = 451;
UPDATE characters SET epithet = 'Incarnation of Love', affiliation = 'Neptune Family', job = 'Queen of the Ryugu Kingdom', status = 'Deceased' WHERE id = 452;
UPDATE characters SET job = 'Noble', status = 'Alive' WHERE id = 453;
UPDATE characters SET affiliation = 'Marines', job = 'Cyborgs' WHERE id = 454;
UPDATE characters SET job = 'Dial Boat Engineer', status = 'Alive' WHERE id = 455;
UPDATE characters SET fruit_name = 'Dragon-Dragon Fruit, Model: Spinosaurus', fruit_type = 'Ancient Zoan', bounty = '290,000,000', affiliation = 'Yamato', job = 'Shinuchi', status = 'Alive' WHERE id = 456;
UPDATE characters SET affiliation = 'Criminal brand', job = 'Fashion Designer', status = 'Alive' WHERE id = 457;
UPDATE characters SET affiliation = 'Baratie', job = 'Patissier', status = 'Alive' WHERE id = 458;
UPDATE characters SET affiliation = 'Galley-La Company', job = 'Vice President of Galley-La', status = 'Alive' WHERE id = 459;
UPDATE characters SET bounty = '52,000,000', affiliation = 'Peachbeard Pirates', job = 'Pirate', status = 'Alive' WHERE id = 460;
UPDATE characters SET epithet = 'Pearl the Iron Wall', affiliation = 'Krieg Pirates', job = 'Commander of the Krieg Pirates '' second unit', status = 'Alive' WHERE id = 461;
UPDATE characters SET epithet = 'Pedro of the Treetops', bounty = '382,000,000', affiliation = 'Mokomo Dukedom', job = 'Captain of the Guardians', status = 'Deceased' WHERE id = 462;
UPDATE characters SET affiliation = 'Galley-La Company', job = 'Dock 1 Foreman', status = 'Alive' WHERE id = 463;
UPDATE characters SET fruit_name = 'Turtle-Turtle Fruit', fruit_type = 'Zoan', bounty = '330,000,000', affiliation = 'Big Mom Pirates', job = 'Combatant', status = 'Unknown' WHERE id = 464;
UPDATE characters SET epithet = 'Pell the Falcon', fruit_name = 'Tweet-Tweet Fruit Falcon Type', fruit_type = 'Zoan', affiliation = 'Arabasta Kingdom', job = 'Commander of Royal Guards', status = 'Alive' WHERE id = 465;
UPDATE characters SET affiliation = 'Heart Pirates', job = 'Pirate', status = 'Unknown' WHERE id = 466;
UPDATE characters SET epithet = 'Ghost Princess', fruit_name = 'Hollow-Hollow Fruit', fruit_type = 'Paramecia', affiliation = 'Thriller Bark Pirates ( Mysterious Four )', job = 'Pirate', status = 'Alive' WHERE id = 467;
UPDATE characters SET fruit_name = 'Stone-Stone Fruit', fruit_type = 'Paramecia', bounty = '99,000,000', affiliation = 'Donquixote Pirates', job = 'Pirate Executive Officer', status = 'Alive' WHERE id = 468;
UPDATE characters SET epithet = 'Tackle Machine', affiliation = 'Foxy Pirates (former)', job = 'Pirate', status = 'Alive' WHERE id = 469;
UPDATE characters SET fruit_name = 'Horse-Horse Fruit', fruit_type = 'Zoan', affiliation = 'Gan Fall', job = 'Gan Fall''s Pet', status = 'Alive' WHERE id = 470;
UPDATE characters SET fruit_name = 'Rattlesnake SMILE', fruit_type = 'Artificial Zoan', affiliation = 'Beasts Pirates , Kurozumi Tama', job = 'Shinuchi', status = 'Alive' WHERE id = 472;
UPDATE characters SET affiliation = 'Foxy Pirates', job = 'Pirate', status = 'Alive' WHERE id = 473;
UPDATE characters SET bounty = '3,400,000', affiliation = 'Bluejam Pirates', job = 'Pirate', status = 'Deceased' WHERE id = 474;
UPDATE characters SET epithet = 'Fire Fist Ace', fruit_name = 'Flame-Flame Fruit', fruit_type = 'Logia', bounty = '550,000,000', affiliation = 'Whitebeard Pirates', job = '2nd Division Commander', status = 'Deceased' WHERE id = 475;
UPDATE characters SET affiliation = 'Gol D. Roger', status = 'Deceased' WHERE id = 476;
UPDATE characters SET affiliation = 'Charlotte Family', status = 'Alive' WHERE id = 477;
UPDATE characters SET fruit_name = 'Glorp-Glorp Fruit', fruit_type = 'Unknown', bounty = '500,000,000', affiliation = 'Marines ( G-14 )', job = 'Rear Admiral', status = 'Alive' WHERE id = 479;
UPDATE characters SET epithet = 'Prometheus the Sun', affiliation = 'Big Mom Pirates', status = 'Unknown' WHERE id = 482;
UPDATE characters SET affiliation = 'Marines , Marine 77th Branch', job = 'Marine Commodore', status = 'Deceased' WHERE id = 483;
UPDATE characters SET affiliation = 'Marines ( SSG ) (former)', status = 'Alive' WHERE id = 484;
UPDATE characters SET epithet = 'Queen the Plague', fruit_name = 'Dragon-Dragon Fruit, Model: Brachiosaurus', fruit_type = 'Ancient Zoan', bounty = '1,320,000,000', affiliation = 'Beasts Pirates', job = 'All-Star', status = 'Alive' WHERE id = 485;
UPDATE characters SET affiliation = 'Big Mom Pirates', status = 'Alive' WHERE id = 486;
UPDATE characters SET epithet = 'Legendary Gambler', affiliation = 'Revolutionary Army', status = 'Alive' WHERE id = 487;
UPDATE characters SET epithet = 'Raizo of the Mist', fruit_name = 'Scrolling Jutsu', fruit_type = 'Paramecia', affiliation = 'Kouzuki Family', job = 'Daimyo', status = 'Alive' WHERE id = 488;
UPDATE characters SET affiliation = 'Shandia', job = 'Shandia Warrior', status = 'Alive' WHERE id = 489;
UPDATE characters SET affiliation = 'Whitebeard Pirates', job = '7th Division Commander', status = 'Alive' WHERE id = 490;
UPDATE characters SET affiliation = 'Subordinate of the Whitebeard Pirates', job = 'Pirate', status = 'Alive' WHERE id = 491;
UPDATE characters SET affiliation = 'Kuja Pirates', job = 'Pirate', status = 'Alive' WHERE id = 492;
UPDATE characters SET epithet = 'Crane Rider', affiliation = 'Big Mom Pirates', job = 'Pirate', status = 'Alive' WHERE id = 493;
UPDATE characters SET affiliation = 'Mecha Island', job = 'Feudal Lord of Mecha Island', status = 'Alive' WHERE id = 494;
UPDATE characters SET epithet = 'The Undefeated Woman', affiliation = 'Dressrosa', job = 'Lady-in-waiting, Gladiator (former), Princess Of Dressrosa (former)', status = 'Alive' WHERE id = 495;
UPDATE characters SET affiliation = 'Cross Guild', job = 'Pet', status = 'Alive' WHERE id = 496;
UPDATE characters SET affiliation = 'Marines ( 153rd Branch )', job = 'Waitress', status = 'Alive' WHERE id = 497;
UPDATE characters SET epithet = 'King of Miracles', affiliation = 'Riku Family', job = 'King', status = 'Alive' WHERE id = 498;
UPDATE characters SET affiliation = 'Kuja Pirates', job = 'Pirate', status = 'Alive' WHERE id = 499;
UPDATE characters SET bounty = '1,000,000', affiliation = 'Marines ( 153rd Branch )', job = 'Marine Commander', status = 'Alive' WHERE id = 500;
UPDATE characters SET epithet = 'Massacre Weapon', fruit_name = 'Cat-Cat Fruit Leopard Model', fruit_type = 'Zoan', affiliation = 'CP0', job = 'Cipher Pol Agent', status = 'Alive' WHERE id = 501;
UPDATE characters SET affiliation = 'Drum Kingdom (former)', job = 'Wapol ''s Pet', status = 'Unknown' WHERE id = 502;
UPDATE characters SET epithet = 'Killers of the Snowy Mountain', bounty = '20,000,000', affiliation = 'Caesar Clown (former)', job = 'Mercenaries', status = 'Unknown' WHERE id = 503;
UPDATE characters SET bounty = '94,000,000', affiliation = 'Red Hair Pirates', job = 'Pirate', status = 'Alive' WHERE id = 504;
UPDATE characters SET affiliation = 'Mokomo Dukedom', job = 'Guardian', status = 'Alive' WHERE id = 505;
UPDATE characters SET affiliation = 'Beasts Pirates ( Numbers )', status = 'Alive' WHERE id = 506;
UPDATE characters SET epithet = 'Pirate Hunter Zoro', bounty = '1,111,000,000', affiliation = 'Straw Hat Pirates', job = 'Master Swordsman', status = 'Alive' WHERE id = 507;
UPDATE characters SET affiliation = 'World Government ( Rosward Family )', job = 'World Noble', status = 'Alive' WHERE id = 508;
UPDATE characters SET affiliation = 'Apis', status = 'Deceased' WHERE id = 509;
UPDATE characters SET affiliation = 'Neptune Family', job = 'Prince of the Ryugu Kingdom', status = 'Alive' WHERE id = 510;
UPDATE characters SET fruit_name = 'Paw-Paw Fruit', fruit_type = 'Artificial Paramecia', affiliation = 'Seraphim ( Pacifista )', status = 'Alive' WHERE id = 511;
UPDATE characters SET fruit_name = 'Dice-Dice Fruit', fruit_type = 'Artificial Paramecia', affiliation = 'Seraphim ( Pacifista )', status = 'Alive' WHERE id = 512;
UPDATE characters SET fruit_name = 'Swim-Swim Fruit', fruit_type = 'Artificial Paramecia', affiliation = 'Seraphim ( Pacifista )', status = 'Alive' WHERE id = 513;
UPDATE characters SET fruit_name = 'Love-Love Fruit', fruit_type = 'Artificial Paramecia', affiliation = 'Seraphim ( Pacifista )', status = 'Alive' WHERE id = 514;
UPDATE characters SET epithet = 'Flame Emperor', fruit_name = 'Flame-Flame Fruit', fruit_type = 'Logia', bounty = '602,000,000', affiliation = 'Revolutionary Army', job = 'Chief of Staff ( 参謀総長 , Sanbō Sōchō ) of the Revolutionary Army', status = 'Alive' WHERE id = 515;
UPDATE characters SET affiliation = 'Impel Down', job = 'Chief Guard ( 獄卒長 , Gokusotsu Chō )', status = 'Alive' WHERE id = 516;
UPDATE characters SET affiliation = 'Marines', job = 'Marine', status = 'Alive' WHERE id = 517;
UPDATE characters SET epithet = 'Don Sai', bounty = '210,000,000', affiliation = 'Happo Navy', job = 'Captain of the Third Ship of the Straw Hat Grand Fleet', status = 'Alive' WHERE id = 518;
UPDATE characters SET fruit_name = 'Mag-Mag Fruit', fruit_type = 'Logia', bounty = '5,000,000,000', affiliation = 'Marines', job = 'Fleet Admiral', status = 'Alive' WHERE id = 521;
UPDATE characters SET affiliation = 'Impel Down', job = 'Chief Guard ( 牢番長 , Rōban Chō )', status = 'Alive' WHERE id = 522;
UPDATE characters SET affiliation = 'Kuja Pirates', job = 'Snake Weapon', status = 'Alive' WHERE id = 523;
UPDATE characters SET epithet = 'Black Leg', bounty = '1,032,000,000', affiliation = 'Straw Hat Pirates', job = 'Cook', status = 'Alive' WHERE id = 524;
UPDATE characters SET epithet = 'Colossal Battleship', fruit_name = 'Huge-Huge Fruit', fruit_type = 'Paramecia', affiliation = 'Blackbeard Pirates', job = 'Titanic Captain (Captain of the Seventh Ship)', status = 'Alive' WHERE id = 525;
UPDATE characters SET affiliation = 'Gaimon', status = 'Alive' WHERE id = 526;
UPDATE characters SET epithet = 'Big Knife Sarquiss', bounty = '38,000,000', affiliation = 'Bellamy Pirates', job = 'First Mate (former)', status = 'Unknown' WHERE id = 527;
UPDATE characters SET epithet = 'Overflowing Sasaki', fruit_name = 'Dragon-Dragon Fruit, Triceratops Model', fruit_type = 'Ancient Zoan', bounty = '472,000,000', affiliation = 'Beasts Pirates ( Tobiroppo )', job = 'Shinuchi', status = 'Alive' WHERE id = 528;
UPDATE characters SET epithet = 'Satori of the Forest', affiliation = 'God''s Army', job = 'Priest of Enel', status = 'Unknown' WHERE id = 529;
UPDATE characters SET affiliation = 'Poseidon', status = 'Alive' WHERE id = 530;
UPDATE characters SET affiliation = 'Riku Family', job = 'Princess (former)', status = 'Deceased' WHERE id = 532;
UPDATE characters SET affiliation = 'Schneider Pirates', job = 'Pirate', status = 'Alive' WHERE id = 533;
UPDATE characters SET epithet = 'Mountain-Eater', affiliation = 'Roger Pirates (former)', job = 'Pirate (former)', status = 'Alive' WHERE id = 534;
UPDATE characters SET epithet = 'Iron Boy', affiliation = 'Beasts Pirates', job = 'Pirate', status = 'Unknown' WHERE id = 535;
UPDATE characters SET epithet = 'Roar of the Sea', fruit_name = 'Tone-Tone Fruit', fruit_type = 'Paramecia', bounty = '350,000,000', affiliation = 'On Air Pirates', job = 'Pirate Captain', status = 'Alive' WHERE id = 536;
UPDATE characters SET epithet = 'Sengoku the Buddha', fruit_name = 'Human-Human Fruit, Model: Buddha', fruit_type = 'Mythical Zoan', affiliation = 'Marines (semi-retired)', job = 'Inspector General', status = 'Alive' WHERE id = 538;
UPDATE characters SET fruit_name = 'Swim-Swim Fruit', fruit_type = 'Paramecia', bounty = '58,000,000', affiliation = 'Donquixote Pirates', job = 'Pirate Officer', status = 'Alive' WHERE id = 539;
UPDATE characters SET bounty = '500,000,000', affiliation = 'Marines (former)', job = 'Marine Officer (former)', status = 'Alive' WHERE id = 540;
UPDATE characters SET affiliation = 'Shandia', status = 'Deceased' WHERE id = 541;
UPDATE characters SET affiliation = 'Heart Pirates', job = 'Pirate', status = 'Unknown' WHERE id = 542;
UPDATE characters SET affiliation = 'Marines ( SSG ) (former)', status = 'Alive' WHERE id = 543;
UPDATE characters SET affiliation = 'Shakky''s Rip-off Bar', job = 'Bartender', status = 'Alive' WHERE id = 544;
UPDATE characters SET affiliation = 'World Government ( Rosward Family )', job = 'World Noble', status = 'Alive' WHERE id = 545;
UPDATE characters SET epithet = 'Nyaban Brothers', bounty = '7,000,000', affiliation = 'Black Cat Pirates', job = 'Pirate Officer', status = 'Alive' WHERE id = 546;
UPDATE characters SET epithet = 'Red-Haired Shanks', bounty = '4,048,900,000', affiliation = 'Red Hair Pirates', job = 'Chief', status = 'Alive' WHERE id = 547;
UPDATE characters SET fruit_name = 'Sheep SMILE', fruit_type = 'Artificial Zoan', affiliation = 'Beasts Pirates', job = 'Shinuchi of the Gifters ( ギフターズ真打ち , Gifutāzu Shin''uchi )', status = 'Unknown' WHERE id = 548;
UPDATE characters SET affiliation = 'Five Elders', job = 'Co-Head of the World Government (Public)', status = 'Alive' WHERE id = 549;
UPDATE characters SET epithet = 'Shiki the Golden Lion', fruit_name = 'Float-Float Fruit', fruit_type = 'Paramecia', affiliation = 'Golden Lion Pirates', job = 'Pirate Captain / Admiral', status = 'Alive' WHERE id = 550;
UPDATE characters SET affiliation = 'Shimotsuki Family', job = 'Swordsmith', status = 'Deceased' WHERE id = 551;
UPDATE characters SET epithet = 'Legendary Samurai', affiliation = 'Wano Country', job = 'Samurai', status = 'Deceased' WHERE id = 552;
UPDATE characters SET job = 'Daimyo of Ringo', status = 'Deceased' WHERE id = 553;
UPDATE characters SET epithet = 'Yasu the Hedgehog', job = 'Taikomochi', status = 'Deceased' WHERE id = 554;
UPDATE characters SET epithet = 'Bewitching Kunoichi', fruit_name = 'Ripe-Ripe Enticement Jutsu', fruit_type = 'Paramecia', affiliation = 'Kouzuki Family', job = 'Kunoichi', status = 'Alive' WHERE id = 555;
UPDATE characters SET epithet = 'Mermaid Princess', affiliation = 'Neptune Family', job = 'Princess of the Ryugu Kingdom', status = 'Alive' WHERE id = 556;
UPDATE characters SET epithet = 'Shiryu of the Rain', fruit_name = 'Clear-Clear Fruit', fruit_type = 'Paramecia', affiliation = 'Blackbeard Pirates', job = 'Titanic Captain (Captain of the Second Ship)', status = 'Alive' WHERE id = 557;
UPDATE characters SET epithet = 'Full Power Shishilian', affiliation = 'Mokomo Dukedom', job = 'Captain of the Musketeers', status = 'Alive' WHERE id = 558;
UPDATE characters SET fruit_name = 'Rust-Rust Fruit', fruit_type = 'Paramecia', bounty = '100,000,000', affiliation = 'Marines', job = 'Marine Captain', status = 'Alive' WHERE id = 559;
UPDATE characters SET epithet = 'Sky Rider', affiliation = 'God''s Army', job = 'Priest of Enel', status = 'Unknown' WHERE id = 560;
UPDATE characters SET epithet = 'Pirate Executioner', affiliation = 'Gasparde Pirates (former)', job = 'Bounty Hunter', status = 'Alive' WHERE id = 561;
UPDATE characters SET epithet = 'Madam Shyarly', affiliation = 'Mermaid Cafe', job = 'Proprietor of the Mermaid Cafe', status = 'Alive' WHERE id = 562;
UPDATE characters SET epithet = 'Dark King', affiliation = 'Roger Pirates (former)', job = 'Coating Mechanic', status = 'Alive' WHERE id = 563;
UPDATE characters SET fruit_name = 'Sala-Sala Fruit, Model: Axolotl', fruit_type = 'Zoan', affiliation = 'Caesar Clown', job = 'Pet , Bio-Chemical weapon of mass destruction', status = 'Deceased' WHERE id = 564;
UPDATE characters SET epithet = 'Smoker the White Hunter', fruit_name = 'Smoke-Smoke Fruit', fruit_type = 'Logia', bounty = '500,000,000', affiliation = 'Marines', job = 'Vice Admiral', status = 'Alive' WHERE id = 565;
UPDATE characters SET fruit_name = 'Monkey SMILE', fruit_type = 'Artificial Zoan', affiliation = 'Beasts Pirates', job = 'Shinuchi', status = 'Alive' WHERE id = 566;
UPDATE characters SET affiliation = 'CP0', job = 'CP0 Chief (former)', status = 'Alive' WHERE id = 568;
UPDATE characters SET affiliation = 'CP9 (former)', job = 'CP9 Chief (former)', status = 'Alive' WHERE id = 569;
UPDATE characters SET fruit_name = 'Horse SMILE', fruit_type = 'Artificial Zoan', affiliation = 'Beasts Pirates (former)', job = 'Shinuchi', status = 'Alive' WHERE id = 570;
UPDATE characters SET affiliation = 'Whitebeard Pirates', job = '14th Division Commander', status = 'Alive' WHERE id = 571;
UPDATE characters SET affiliation = 'World Government , Impel Down', job = 'Level 2 Guardian', status = 'Alive' WHERE id = 572;
UPDATE characters SET affiliation = 'Thriller Bark Victim''s Association', job = 'Chairman of Thriller Bark Victim''s Association', status = 'Alive' WHERE id = 573;
UPDATE characters SET epithet = 'Maelstrom Spider', bounty = '210,000,000', affiliation = 'Maelstrom Spider Pirates', job = 'Pirate Captain', status = 'Alive' WHERE id = 574;
UPDATE characters SET bounty = '500,000,000', affiliation = 'Marines', job = 'Vice Admiral', status = 'Alive' WHERE id = 575;
UPDATE characters SET job = 'King of the Goa Kingdom', status = 'Alive' WHERE id = 576;
UPDATE characters SET bounty = '500,000,000', affiliation = 'Marines', job = 'Vice Admiral', status = 'Alive' WHERE id = 577;
UPDATE characters SET epithet = 'Gourmet Knight', fruit_name = 'Cook-Cook Fruit', fruit_type = 'Paramecia', affiliation = 'Big Mom Pirates', job = 'Executive Chef', status = 'Alive' WHERE id = 578;
UPDATE characters SET fruit_name = 'Horse-Horse Fruit, Pegasus Model', fruit_type = 'Mythical Zoan', affiliation = 'Blackbeard Pirates', job = 'Doc Q''s horse', status = 'Alive' WHERE id = 579;
UPDATE characters SET epithet = 'Queen of the Pleasure District', fruit_type = 'Zoan', affiliation = 'Vegapunk', job = 'Spy', status = 'Unknown' WHERE id = 580;
UPDATE characters SET fruit_name = 'Hobby-Hobby Fruit', fruit_type = 'Paramecia', affiliation = 'Donquixote Pirates', job = 'Pirate Special Officer', status = 'Alive' WHERE id = 581;
UPDATE characters SET epithet = 'Suleiman the Beheader', bounty = '67,000,000', affiliation = 'Beautiful Pirates', job = 'Pirate', status = 'Alive' WHERE id = 582;
UPDATE characters SET affiliation = 'Arabasta Kingdom Guard Squad' WHERE id = 584;
UPDATE characters SET affiliation = 'New Fish-Man Pirates (defected)', job = 'Pet', status = 'Alive' WHERE id = 585;
UPDATE characters SET affiliation = 'Kuja Pirates', job = 'Pirate', status = 'Alive' WHERE id = 586;
UPDATE characters SET epithet = 'Ship Cutter', bounty = '500,000,000', affiliation = 'Marines', job = 'Marine Vice Admiral', status = 'Deceased' WHERE id = 587;
UPDATE characters SET epithet = 'Baron Tamago', fruit_name = 'Egg-Egg Fruit', fruit_type = 'Zoan', bounty = '429,000,000', affiliation = 'Big Mom Pirates', job = 'Combatant', status = 'Alive' WHERE id = 589;
UPDATE characters SET fruit_name = 'Through-Through Fruit', fruit_type = 'Paramecia', affiliation = 'Gran Tesoro', job = 'Security Guard', status = 'Alive' WHERE id = 590;
UPDATE characters SET affiliation = 'Thriller Bark Pirates', job = 'General Zombie', status = 'Deceased' WHERE id = 591;
UPDATE characters SET bounty = '100,000,000', affiliation = 'Marines', job = 'Captain', status = 'Alive' WHERE id = 592;
UPDATE characters SET affiliation = 'Arabasta Kingdom', job = 'Royal Head Chef', status = 'Alive' WHERE id = 593;
UPDATE characters SET affiliation = 'Revolutionary Army', job = 'Revolutionary Army Intelligence Controller', status = 'Alive' WHERE id = 594;
UPDATE characters SET affiliation = 'Whitebeard Pirates', job = '4th Division Commander', status = 'Deceased' WHERE id = 595;
UPDATE characters SET affiliation = 'Galley-La Company', job = 'Dock One Foreman', status = 'Alive' WHERE id = 598;
UPDATE characters SET bounty = '500,000,000', affiliation = 'Marines', job = 'Vice Admiral', status = 'Alive' WHERE id = 599;
UPDATE characters SET affiliation = 'Kouzuki Hiyori , Shimotsuki Family', job = 'Kamuro', status = 'Alive' WHERE id = 600;
UPDATE characters SET affiliation = 'Tom''s Workers', job = 'Shipwright', status = 'Deceased' WHERE id = 601;
UPDATE characters SET job = 'Nomad, Stilt walker', status = 'Alive' WHERE id = 602;
UPDATE characters SET epithet = 'Cotton Candy Lover', fruit_name = 'Human-Human Fruit', fruit_type = 'Zoan', bounty = '1,000', affiliation = 'Straw Hat Pirates', job = 'Doctor', status = 'Alive' WHERE id = 603;
UPDATE characters SET affiliation = 'Poseidon', status = 'Alive' WHERE id = 604;
UPDATE characters SET affiliation = 'Five Elders', job = 'Co-Head of the World Government (Public)', status = 'Alive' WHERE id = 605;
UPDATE characters SET epithet = 'Demon King of Songs', status = 'Unknown' WHERE id = 606;
UPDATE characters SET affiliation = 'Koza', job = 'Yuba villager', status = 'Alive' WHERE id = 607;
UPDATE characters SET status = 'Deceased' WHERE id = 609;
UPDATE characters SET epithet = 'Surgeon of Death', fruit_name = 'Op-Op Fruit', fruit_type = 'Paramecia', bounty = '3,000,000,000', affiliation = 'Heart Pirates', job = 'Pirate Captain', status = 'Alive' WHERE id = 610;
UPDATE characters SET fruit_name = 'Stick-Stick Fruit', fruit_type = 'Paramecia', bounty = '99,000,000', affiliation = 'Donquixote Pirates', job = 'Pirate Executive Officer', status = 'Alive' WHERE id = 611;
UPDATE characters SET affiliation = 'Mokomo Dukedom', job = 'Nurse', status = 'Alive' WHERE id = 612;
UPDATE characters SET affiliation = 'Newkama Land (former)', job = 'Dancer', status = 'Alive' WHERE id = 613;
UPDATE characters SET epithet = 'Great Staff Officer', fruit_name = 'Wash-Wash Fruit', fruit_type = 'Paramecia', bounty = '500,000,000', affiliation = 'Marines', job = 'Vice Admiral', status = 'Alive' WHERE id = 614;
UPDATE characters SET job = 'Tea House Owner', status = 'Alive' WHERE id = 615;
UPDATE characters SET epithet = 'Brutal Bull', affiliation = 'Corrida Colosseum', job = 'Gladiator', status = 'Alive' WHERE id = 617;
UPDATE characters SET fruit_name = 'Dragon-Dragon Fruit, Pachycephalosaurus Model', fruit_type = 'Ancient Zoan', bounty = '400,000,000', affiliation = 'Yamato', job = 'Shinuchi (former)', status = 'Alive' WHERE id = 618;
UPDATE characters SET job = 'Sumo Wrestler', status = 'Alive' WHERE id = 619;
UPDATE characters SET epithet = 'Mad Monk', bounty = '108,000,000', affiliation = 'Fallen Monk Pirates', job = 'Pirate Captain', status = 'Alive' WHERE id = 620;
UPDATE characters SET affiliation = 'Newkama Land (former)', job = 'Dancer, Prisoner of the Great Prison (former)', status = 'Alive' WHERE id = 621;
UPDATE characters SET epithet = 'King of Snipers', bounty = '500,000,000', affiliation = 'Straw Hat Pirates', job = 'Sniper', status = 'Alive' WHERE id = 622;
UPDATE characters SET fruit_name = 'Sing-Sing Fruit', fruit_type = 'Paramecia', affiliation = 'Red Hair Pirates (former)', job = 'Singer', status = 'Unknown' WHERE id = 624;
UPDATE characters SET affiliation = 'Uzuki Family', job = 'Samurai', status = 'Deceased' WHERE id = 625;
UPDATE characters SET epithet = 'The Supersonic', fruit_name = 'Warp-Warp Fruit', fruit_type = 'Paramecia', bounty = '64,000,000', affiliation = 'Blackbeard Pirates', job = 'Titanic Captain (Captain of the Third Ship)', status = 'Alive' WHERE id = 626;
UPDATE characters SET fruit_name = 'Mark-Mark Fruit', fruit_type = 'Paramecia', affiliation = 'Flying Pirates', job = 'Pirate Captain', status = 'Alive' WHERE id = 627;
UPDATE characters SET epithet = 'Heavy Drinker Vasco Shot', fruit_name = 'Glug-Glug Fruit', fruit_type = 'Paramecia', affiliation = 'Blackbeard Pirates', job = 'Titanic Captain (Captain of the Eighth Ship)', status = 'Alive' WHERE id = 628;
UPDATE characters SET affiliation = 'Vegapunk', status = 'Destroyed' WHERE id = 629;
UPDATE characters SET epithet = 'The Man With the Best Brain in the World', fruit_name = 'Brain-Brain Fruit', fruit_type = 'Paramecia', affiliation = 'MADS (former)', job = 'Scientist', status = 'Deceased' WHERE id = 630;
UPDATE characters SET epithet = 'Demon Bamboo Vergo', affiliation = 'Donquixote Pirates', job = 'Pirate Elite Officer', status = 'Deceased' WHERE id = 631;
UPDATE characters SET fruit_name = 'Berry-Berry Fruit', fruit_type = 'Paramecia', bounty = '100,000,000', affiliation = 'Marines', job = 'Marine Captain', status = 'Alive' WHERE id = 632;
UPDATE characters SET affiliation = 'Thriller Bark Pirates', job = 'Actress (in life)', status = 'Deceased' WHERE id = 633;
UPDATE characters SET epithet = 'Sparking Red', affiliation = 'Vinsmoke Family', job = 'Prince', status = 'Alive' WHERE id = 634;
UPDATE characters SET epithet = 'Garuda', affiliation = 'Vinsmoke Family', job = 'King of the Germa Kingdom', status = 'Alive' WHERE id = 635;
UPDATE characters SET epithet = 'Dengeki Blue', affiliation = 'Vinsmoke Family', job = 'Prince', status = 'Alive' WHERE id = 636;
UPDATE characters SET epithet = 'Poison Pink', affiliation = 'Vinsmoke Family', job = 'Princess', status = 'Alive' WHERE id = 637;
UPDATE characters SET affiliation = 'Vinsmoke Family', job = 'Queen of the Germa Kingdom', status = 'Deceased' WHERE id = 638;
UPDATE characters SET epithet = 'Winch Green', affiliation = 'Vinsmoke Family', job = 'Prince', status = 'Alive' WHERE id = 639;
UPDATE characters SET fruit_name = 'Glare-Glare Fruit', fruit_type = 'Paramecia', affiliation = 'Riku Family', job = 'Princess of Dressrosa', status = 'Alive' WHERE id = 640;
UPDATE characters SET epithet = 'Vista of the Flower Swords', affiliation = 'Whitebeard Pirates (former)', job = '5th Division Commander (former)', status = 'Alive' WHERE id = 641;
UPDATE characters SET epithet = 'Monster Gun', bounty = '95,000,000', affiliation = 'Fire Tank Pirates', job = 'Pirate , Advisor', status = 'Alive' WHERE id = 642;
UPDATE characters SET epithet = 'Large Monk', affiliation = 'Sun Pirates', job = 'Pirate', status = 'Alive' WHERE id = 643;
UPDATE characters SET affiliation = 'Mokomo Dukedom', job = 'Musketeer', status = 'Alive' WHERE id = 644;
UPDATE characters SET epithet = 'Mad Wanze', affiliation = 'CP7', job = 'Cipher Pol Agent', status = 'Alive' WHERE id = 645;
UPDATE characters SET epithet = 'Tin-Plate Wapol', fruit_name = 'Munch-Munch Fruit', fruit_type = 'Paramecia', affiliation = 'Evil Black Drum Kingdom', job = 'King of the Evil Black Drum Kingdom', status = 'Alive' WHERE id = 646;
UPDATE characters SET epithet = 'Whitebeard', fruit_name = 'Tremor-Tremor Fruit', fruit_type = 'Paramecia', bounty = '5,046,000,000', affiliation = 'Whitebeard Pirates', job = 'Pirate Captain', status = 'Deceased' WHERE id = 647;
UPDATE characters SET epithet = 'Ice Witch', affiliation = 'Whitebeard Pirates', job = 'Pirate', status = 'Alive' WHERE id = 648;
UPDATE characters SET epithet = 'Who of the Droplets', fruit_name = 'Cat-Cat Fruit, Saber-Toothed Tiger Model', fruit_type = 'Ancient Zoan', bounty = '546,000,000', affiliation = 'Beasts Pirates ( Tobiroppo )', job = 'Shinuchi', status = 'Alive' WHERE id = 649;
UPDATE characters SET affiliation = 'Kid Pirates', job = 'Pirate', status = 'Unknown' WHERE id = 650;
UPDATE characters SET affiliation = 'Foosha Village', job = 'Mayor', status = 'Alive' WHERE id = 651;
UPDATE characters SET epithet = 'Berserker', affiliation = 'Shandia', job = 'Shandia Warrior', status = 'Alive' WHERE id = 652;
UPDATE characters SET epithet = 'Red Flag', fruit_name = 'Dragon-Dragon Fruit, Model: Allosaurus', fruit_type = 'Ancient Zoan', bounty = '222,000,000', affiliation = 'Marines ( SWORD )', job = 'Captain of SWORD', status = 'Alive' WHERE id = 653;
UPDATE characters SET affiliation = 'Enel (former)', job = 'Commander of the Divine Soldiers (former)', status = 'Unknown' WHERE id = 654;
UPDATE characters SET bounty = '500,000,000', affiliation = 'Marines', job = 'Vice Admiral', status = 'Alive' WHERE id = 655;
UPDATE characters SET epithet = 'Oni Princess', fruit_name = 'Dog-Dog Fruit, Model: Okuchi-no-Makami', fruit_type = 'Mythical Zoan', affiliation = 'Ninja-Pirate-Mink-Samurai Alliance (disbanded)', status = 'Alive' WHERE id = 656;
UPDATE characters SET epithet = 'Chaser', affiliation = 'Red Hair Pirates', job = 'Pirate', status = 'Alive' WHERE id = 657;
UPDATE characters SET affiliation = 'Tom''s Workers (former)', status = 'Alive' WHERE id = 658;
UPDATE characters SET affiliation = 'World Government', job = 'Scientist', status = 'Alive' WHERE id = 659;
UPDATE characters SET epithet = 'Calico Yorki', affiliation = 'Rumbar Pirates', job = 'Pirate', status = 'Unknown' WHERE id = 660;
UPDATE characters SET affiliation = 'Johnny', job = 'Bounty Hunter (former)', status = 'Alive' WHERE id = 661;
UPDATE characters SET status = 'Alive' WHERE id = 663;
UPDATE characters SET epithet = 'Black Arm Zephyr', affiliation = 'Neo Marines', job = 'Neo Marines Supreme Commander', status = 'Deceased' WHERE id = 664;
UPDATE characters SET affiliation = 'Galley-La Company (Zambai''s Company Union)', job = 'Dismantler', status = 'Alive' WHERE id = 665;
UPDATE characters SET epithet = 'Red-Leg Zeff', affiliation = 'Baratie', job = 'Head Chef of Baratie , Pirate Captain (former)', status = 'Alive' WHERE id = 666;
UPDATE characters SET epithet = 'Noble of the Fish-Man District', affiliation = 'New Fish-Man Pirates', job = 'Pirate', status = 'Alive' WHERE id = 667;
UPDATE characters SET epithet = 'Zeus the Thundercloud', affiliation = 'Straw Hat Pirates', job = 'Partner ( 相棒 , Aibō , Viz: Sidekick)', status = 'Alive' WHERE id = 668;
UPDATE characters SET affiliation = 'Straw Hat Pirates', status = 'Active' WHERE id = 696;
