UPDATE characters SET fruit_name = 'Goe Goe Fruit', fruit_type = 'Paramecia', bounty = '10,000,000', affiliation = 'Eldoraggo Pirates', job = 'Pirate Captain', status = 'Alive' WHERE id = 178;
UPDATE characters SET epithet = 'The Fighting King', affiliation = 'Prodence Kingdom', job = 'King', status = 'Alive' WHERE id = 179;
UPDATE characters SET affiliation = 'Subordinate of the Whitebeard Pirates', job = 'Pirate', status = 'Alive' WHERE id = 180;
UPDATE characters SET epithet = 'Iron Giant', status = 'Unknown' WHERE id = 181;
UPDATE characters SET epithet = 'Okama King', fruit_name = 'Horm-Horm Fruit', fruit_type = 'Paramecia', bounty = '100,000,000', affiliation = 'Revolutionary Army', job = 'G Army Commander of the Revolutionary Army', status = 'Alive' WHERE id = 182;
UPDATE characters SET epithet = 'God Enel', fruit_name = 'Rumble-Rumble Fruit', fruit_type = 'Logia', affiliation = 'God''s Army (former)', job = 'God of Skypiea (former)', status = 'Alive' WHERE id = 183;
UPDATE characters SET epithet = 'Eric the Whirlwind', fruit_name = 'Sickle-Sickle Fruit', fruit_type = 'Paramecia', affiliation = '8th Branch (betrayed)', job = 'Mercenary', status = 'Alive' WHERE id = 184;
UPDATE characters SET affiliation = 'Five Elders', job = 'Co-Head of the World Government (Public)', status = 'Alive' WHERE id = 185;
UPDATE characters SET epithet = 'Captain', fruit_name = 'Magnet-Magnet Fruit', fruit_type = 'Paramecia', bounty = '3,000,000,000', affiliation = 'Kid Pirates', job = 'Pirate Captain', status = 'Unknown' WHERE id = 186;
UPDATE characters SET bounty = '26,000,000' WHERE id = 187;
UPDATE characters SET epithet = 'The Adventurer', bounty = '230,000,000', affiliation = 'Sun Pirates', job = 'Adventurer', status = 'Deceased' WHERE id = 188;
UPDATE characters SET affiliation = 'World Government ( World Nobles )', job = 'Highest Authorities of the World Government (Publicly)' WHERE id = 189;
UPDATE characters SET affiliation = 'Whitebeard Pirates', job = '15th Division Commander', status = 'Alive' WHERE id = 190;
UPDATE characters SET fruit_name = 'Chicken SMILE', fruit_type = 'Artificial Zoan', affiliation = 'Beasts Pirates', job = 'Shinuchi', status = 'Alive' WHERE id = 191;
UPDATE characters SET epithet = 'Silver Fox', fruit_name = 'Slow-Slow Fruit', fruit_type = 'Paramecia', bounty = '24,000,000', affiliation = 'Foxy Pirates', job = 'Pirate Captain', status = 'Alive' WHERE id = 192;
UPDATE characters SET bounty = '24,000,000' WHERE id = 193;
UPDATE characters SET epithet = 'Iron Man" Franky', bounty = '394,000,000', affiliation = 'Straw Hat Pirates', job = 'Shipwright', status = 'Alive' WHERE id = 194;
UPDATE characters SET job = 'Samurai', status = 'Deceased' WHERE id = 195;
UPDATE characters SET affiliation = 'Neptune Family', job = 'Prince of the Ryugu Kingdom', status = 'Alive' WHERE id = 196;
UPDATE characters SET affiliation = 'Kurozumi Family', job = 'Ninja', status = 'Unknown' WHERE id = 197;
UPDATE characters SET epithet = 'Fukurou the Silent', affiliation = 'CP0', job = 'Cipher Pol Agent', status = 'Alive' WHERE id = 198;
UPDATE characters SET epithet = 'Double Ironfist Fullbody', bounty = '1,000,000', affiliation = 'Marines', job = 'Marine Lieutenant Commander', status = 'Alive' WHERE id = 199;
UPDATE characters SET fruit_name = 'Elephant-Elephant Fruit', fruit_type = 'Zoan', affiliation = 'CP0 , CP9 (former)', job = 'Spandam ''s sword', status = 'Alive' WHERE id = 200;
UPDATE characters SET affiliation = 'God''s Army', job = 'Battle Pet', status = 'Alive' WHERE id = 201;
UPDATE characters SET epithet = 'Howling" Gab', affiliation = 'Red Hair Pirates', job = 'Pirate', status = 'Alive' WHERE id = 202;
UPDATE characters SET job = 'Guardian of the Island of Rare Animals', status = 'Alive' WHERE id = 203;
UPDATE characters SET epithet = 'Loan Shark', fruit_name = 'Wax-Wax Fruit', fruit_type = 'Paramecia', bounty = '24,000,000', affiliation = 'Cross Guild', job = 'Pirate', status = 'Alive' WHERE id = 204;
UPDATE characters SET epithet = 'Knight of the Sky', affiliation = 'Skypiea', job = 'God of Skypiea', status = 'Alive' WHERE id = 205;
UPDATE characters SET epithet = 'General Gasparde', fruit_name = 'Ame Ame Fruit', fruit_type = 'Logia', bounty = '95,000,000', affiliation = 'Gasparde Pirates', job = 'Pirate Captain', status = 'Unknown' WHERE id = 206;
UPDATE characters SET affiliation = 'Corrida Colosseum', job = 'Announcer', status = 'Alive' WHERE id = 207;
UPDATE characters SET fruit_name = 'Shadow-Shadow Fruit', fruit_type = 'Paramecia', bounty = '320,000,000', affiliation = 'Thriller Bark Pirates ( Mysterious Four )', job = 'Pirate Captain', status = 'Alive' WHERE id = 208;
UPDATE characters SET epithet = 'Sky Boss', affiliation = 'Ukkari Hot-Spring Island', job = 'Priest of Enel (former), Head Clerk of Hot Springs Resort', status = 'Alive' WHERE id = 209;
UPDATE characters SET affiliation = 'Shandia', job = 'Shandia Warrior', status = 'Alive' WHERE id = 210;
UPDATE characters SET affiliation = 'Cocoyasi Village', job = 'Sheriff of Cocoyasi Village', status = 'Alive' WHERE id = 211;
UPDATE characters SET epithet = 'Golden Emperor', fruit_name = 'Gol-Gol Fruit', fruit_type = 'Paramecia', affiliation = 'Gran Tesoro', job = 'Proprietor (former)', status = 'Alive' WHERE id = 212;
UPDATE characters SET epithet = 'Gin the "Man-Demon', bounty = '12,000,000', affiliation = 'Krieg Pirates', job = 'Pirate', status = 'Alive' WHERE id = 213;
UPDATE characters SET affiliation = 'Foxy Pirates (former)', job = 'Shipwright', status = 'Alive' WHERE id = 214;
UPDATE characters SET bounty = '190,000,000', affiliation = 'Revolutionary Army (East Army)', job = 'East Army Captain of the Revolutionary Army, Slave (former)', status = 'Deceased' WHERE id = 215;
UPDATE characters SET fruit_name = 'Squirrel SMILE', fruit_type = 'Artificial Zoan', affiliation = 'Beasts Pirates', job = 'Shinuchi', status = 'Unknown' WHERE id = 216;
UPDATE characters SET fruit_name = 'Art-Art Fruit', fruit_type = 'Paramecia', affiliation = 'Donquixote Pirates', job = 'Pirate Officer', status = 'Alive' WHERE id = 217;
UPDATE characters SET bounty = '500,000,000', affiliation = 'Marines', job = 'Vice Admiral', status = 'Alive' WHERE id = 218;
UPDATE characters SET affiliation = 'Mokomo Dukedom', job = 'Three Inuarashi Musketeers', status = 'Alive' WHERE id = 219;
UPDATE characters SET affiliation = 'CP0', job = 'Cipher Pol Agent', status = 'Alive' WHERE id = 221;
