UPDATE characters SET epithet = 'Master of the Gun', fruit_name = 'Grab-Grab Fruit', fruit_type = 'Paramecia', bounty = '2,009,430,000', affiliation = 'Wandering Clan', job = 'Adventurer', status = 'Unknown' WHERE id = 4;
UPDATE characters SET epithet = 'Sweeper', bounty = '105,500,000', affiliation = 'Big Mom Pirates', job = 'Combatant', status = 'Unknown' WHERE id = 63;
UPDATE characters SET affiliation = 'God Guardians', job = 'Law enforcement official', status = 'Alive' WHERE id = 89;
UPDATE characters SET affiliation = 'Space Pirates', job = 'Captain , Pirate', status = 'Alive' WHERE id = 90;
UPDATE characters SET fruit_name = 'Lion SMILE', fruit_type = 'Artificial Zoan', affiliation = 'Beasts Pirates', job = 'Shinuchi', status = 'Alive' WHERE id = 258;
UPDATE characters SET epithet = 'Jigoro of the Wind', affiliation = 'Thriller Bark Pirates', job = 'General Zombie', status = 'Deceased' WHERE id = 291;
UPDATE characters SET affiliation = 'Wano Country', job = 'Yakuza' WHERE id = 348;
UPDATE characters SET affiliation = 'Automata', job = 'First Lieutenant', status = 'Alive' WHERE id = 356;
UPDATE characters SET bounty = '550,000,000', affiliation = 'Little Pirates', job = 'Pirate Captain', status = 'Unknown' WHERE id = 362;
UPDATE characters SET affiliation = 'Poseidon', status = 'Alive' WHERE id = 363;
UPDATE characters SET bounty = '50,000,000', job = 'Pirate', status = 'Alive' WHERE id = 394;
UPDATE characters SET fruit_type = 'Artificial Zoan', affiliation = 'Beasts Pirates', job = 'Gifter', status = 'Alive' WHERE id = 395;
UPDATE characters SET fruit_name = 'Turtle-Turtle Fruit', fruit_type = 'Zoan', bounty = '330,000,000', affiliation = 'Big Mom Pirates', job = 'Combatant', status = 'Unknown' WHERE id = 425;
UPDATE characters SET affiliation = 'Marines , Mary Geoise , G-8', job = 'Chefs , Dishwashers', status = 'Alive' WHERE id = 445;
UPDATE characters SET affiliation = 'Corrida Colosseum (former)', job = 'Gladiator (former)', status = 'Alive' WHERE id = 448;
UPDATE characters SET affiliation = 'Unnamed kingdom (former)', job = 'Pirate', status = 'Alive' WHERE id = 478;
UPDATE characters SET affiliation = 'Ohara Archaeologists', job = 'Professor and archaeologist of the Tree of Knowledge', status = 'Deceased' WHERE id = 481;
UPDATE characters SET affiliation = 'World Government (former)', job = 'World Noble (former)', status = 'Deceased' WHERE id = 519;
UPDATE characters SET affiliation = 'World Government ( Donquixote Family )', job = 'World Noble', status = 'Deceased' WHERE id = 520;
UPDATE characters SET affiliation = 'Straw Hat Pirates', status = 'Active' WHERE id = 583;
UPDATE characters SET affiliation = 'Perona', job = 'Wild Zombies', status = 'Deceased' WHERE id = 597;
UPDATE characters SET affiliation = 'Sakura Kingdom', job = 'Doctors' WHERE id = 616;
UPDATE characters SET affiliation = 'Marines , Mary Geoise , G-8', job = 'Chefs , Dishwashers', status = 'Alive' WHERE id = 662;
