INSERT INTO illustrators (id,slug,name,source) VALUES (1,'ai-nina','Ai Nina','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (2,'aidle-co-ltd','Aidle Co. Ltd.','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (3,'akagi','akagi','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (4,'akanegumo','Akanegumo','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (5,'akihiro-miyano','Akihiro MIYANO','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (6,'akihiro-ota','akihiro ota','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (7,'akiko-sugizono','Akiko Sugizono','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (8,'akira-egawa','AKIRA EGAWA','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (9,'akira-kano','Akira Kano','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (10,'amano-yoichi','Amano Yoichi','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (11,'anderson','Anderson','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (12,'anthony-nguyen','Anthony Nguyen','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (13,'aosora','aosora','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (14,'asaki-kuroda','ASAKI KURODA','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (15,'ayaka-tsuji','Ayaka Tsuji','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (16,'bahi-jd','Bahi JD','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (17,'bashikou','Bashikou','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (18,'berry-verrine','Berry Verrine','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (19,'bikku','bikku','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (20,'bisai','BISAI','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (21,'chansard-vincent','Chansard Vincent','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (22,'chiharu-akakura','Chiharu Akakura','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (23,'chris','Chris','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (24,'coga','COGA','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (25,'dai-xt','DAI-XT.','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (26,'daiki-ihara','Daiki Ihara','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (27,'daisuke-enoshima','Daisuke Enoshima','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (28,'daisuke-izuka','Daisuke Izuka','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (29,'demizu-posuka','Demizu Posuka','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (30,'denim2','Denim2','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (31,'ebimo','EBIMO','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (32,'eiji-kaneda','eiji kaneda','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (33,'eri-yonemoto','Eri Yonemoto','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (34,'futa','Futa','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (35,'fuyuko-iwata','Fuyuko Iwata','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (36,'game','Game','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (37,'gege-akutami','Gege Akutami','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (38,'gidora','GIDORA','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (39,'hachi-takashi','Hachi Takashi','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (40,'hagane-tsurugi','Hagane Tsurugi','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (41,'hanao-iida','hanao iida','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (42,'haru-miyajima','Haru Miyajima','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (43,'hashimoto-q','Hashimoto Q','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (44,'hatori-kyoka','Hatori Kyoka','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (45,'hayaken-sarena','Hayaken-sarena','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (46,'he-ziwei','He Ziwei','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (47,'henry-thurlow','Henry Thurlow','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (48,'hidano-kentaro','Hidano Kentaro','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (49,'hirado-sanpei','HIRADO SANPEI','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (50,'hirotaka-ito','Hirotaka Ito','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (51,'hiroto-saito','Hiroto Saito','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (52,'hisashi-hujiwara','HISASHI HUJIWARA','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (53,'hmng','hmng','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (54,'hokuyuu','Hokuyuu','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (55,'honehone','Honehone','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (56,'itsuki-tsuchigami','Itsuki Tsuchigami','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (57,'joji-yamada','Joji Yamada','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (58,'jugemt','jugemt','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (59,'k-akagishi','K Akagishi','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (60,'kaito-shibano','Kaito Shibano','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (61,'kaito-tomioka','Kaito Tomioka','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (62,'kang-qiyun','Kang QiYun','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (63,'kankurou','kankurou','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (64,'kaoru-hagiya','KAORU HAGIYA','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (65,'katsumi-ishizuka','Katsumi Ishizuka','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (66,'katsuo-tadano','Katsuo Tadano','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (67,'kawaguchi-yuki','Kawaguchi Yuki','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (68,'kazuno-yuikawa','Kazuno Yuikawa','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (69,'kazuyuki-hayashi','Kazuyuki Hayashi','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (70,'keiichi-ichikawa','Keiichi Ichikawa','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (71,'keisuke-mori','Keisuke Mori','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (72,'kentaro-hidano','Kentaro Hidano','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (73,'kento-amemiya','Kento Amemiya','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (74,'kento-terasaka','Kento Terasaka','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (75,'kicori','kicori','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (76,'kisuke','KISUKE','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (77,'kito','kito','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (78,'kohei-hirota','Kohei Hirota','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (79,'kohei-mikoshi','Kohei Mikoshi','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (80,'kou-takase','kou takase','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (81,'kou-tasake','kou tasake','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (82,'koushi-rokushiro','Koushi Rokushiro','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (83,'koutaro-sugi','KOUTARO SUGI','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (84,'kudo-sakiko','kudo sakiko','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (85,'kusunoki-harui','kusunoki harui','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (86,'kyosuke-usuta','Kyosuke Usuta','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (87,'lack','lack','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (88,'m-miyokura','M_miyokura','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (89,'m-romayasu','M_romayasu','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (90,'makitoshi','Makitoshi','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (91,'makoto-muroi','Makoto Muroi','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (92,'mamoru-yokota','Mamoru Yokota','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (93,'masaya-hasegawa','Masaya Hasegawa','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (94,'matsumoto-akira','Matsumoto Akira','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (95,'mayu-sakai','Mayu Sakai','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (96,'mehdi-aouichaoui','Mehdi Aouichaoui','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (97,'melo-kyuba','Melo Kyuba','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (98,'miche-boureikoubou','Miche(BoureiKoubou)','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (99,'midori-matsuda','Midori Matsuda','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (100,'miho-midorikawa','Miho Midorikawa','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (101,'minato-sashima','Minato Sashima','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (102,'misa-matoki','Misa Matoki','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (103,'misa-tsutsui','Misa Tsutsui','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (104,'mitsuaki-matsumoto','Mitsuaki Matsumoto','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (105,'mmmkawaine','mmmkawaine','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (106,'moeka-araki','Moeka Araki','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (107,'moopic','Moopic','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (108,'morechand','Morechand','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (109,'moroi','MOROI','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (110,'mushimaro','mushimaro','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (111,'mutsumi-sasaki','Mutsumi Sasaki','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (112,'nakamaru','Nakamaru','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (113,'nakano-haito','Nakano Haito','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (114,'nakanoryo','NAKANORYO','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (115,'nakauma','NAKAuMA','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (116,'naochika-morishita','Naochika Morishita','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (117,'naoshi-komi','NAOSHI KOMI','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (118,'naruse-uroko','Naruse Uroko','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (119,'nekobayashi','Nekobayashi','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (120,'nico-tine','Nico-Tine','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (121,'niiii','Niiii','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (122,'nijihayashi','Nijihayashi','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (123,'nijimaarc','NIJIMAARC','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (124,'nishinoshima','nishinoshima','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (125,'noriko-asaka','Noriko Asaka','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (126,'norikoi','Norikoi','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (127,'noriyuki-hirota','Noriyuki Hirota','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (128,'nuisuke','nuisuke','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (129,'nukadokomogera','nukadokomogera','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (130,'odashi','odashi','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (131,'oden','Oden','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (132,'ono-tako','Ono Tako','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (133,'otton','otton','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (134,'otumami','otumami','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (135,'ou-jyunce','Ou Jyunce','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (136,'paji','Paji','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (137,'peach-momoko','Peach Momoko','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (138,'penekor','PENEKOR','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (139,'phima','phima','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (140,'pisuke','Pisuke','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (141,'pokimari','POKImari','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (142,'rina-fujii','Rina Fujii','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (143,'rina-usui','Rina Usui','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (144,'rofta','Rofta','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (145,'romayasu','Romayasu','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (146,'ryo-nakama','Ryo Nakama','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (147,'ryuda','Ryuda','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (148,'s-kinoko','S-KINOKO','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (149,'s-on','s!on','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (150,'sacanahen','sacanahen','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (151,'samei-ikusa','Samei Ikusa','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (152,'saya-tsuruta','Saya Tsuruta','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (153,'sennsu','SENNSU','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (154,'shachinomaru','Shachinomaru','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (155,'shie-nanahara','SHIE NANAHARA','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (156,'shigefumi-shingaki','Shigefumi Shingaki','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (157,'shin-kashiwaguma','Shin Kashiwaguma','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (158,'shinnosuke-tanaka','Shinnosuke Tanaka','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (159,'shinra-agency-co-ltd','SHINRA AGENCY Co. Ltd.','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (160,'shishizaru','Shishizaru','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (161,'sho','sho','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (162,'shosuke','shosuke','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (163,'shuhei-miyazaki','Shuhei Miyazaki','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (164,'shun-saeki','Shun Saeki','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (165,'sohin','sohin','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (166,'sowsow','SOWSOW','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (167,'sto1e','sto1e','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (168,'studio-vigor-co-ltd','Studio Vigor Co. Ltd','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (169,'suemi-jun','Suemi jun','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (170,'sunohara','Sunohara','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (171,'suzume-muraichi','Suzume Muraichi','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (172,'tacchan','Tacchan','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (173,'tadahiro-miura','Tadahiro Miura','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (174,'tadaichi-nakama','Tadaichi Nakama','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (175,'takamasa-moue','Takamasa Moue','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (176,'takashi-kojima','Takashi Kojima','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (177,'takashi-yoshiike','Takashi Yoshiike','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (178,'takeshi-maenami','Takeshi Maenami','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (179,'takeuchiryosuke','TakeuchiRyosuke','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (180,'takumi-ishikawa','Takumi Ishikawa','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (181,'tamerlan-bekmurzaye','Tamerlan Bekmurzaye','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (182,'tanaka-kenichi','Tanaka Kenichi','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (183,'tapioca','TAPIOCA','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (184,'tasaka','tasaka','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (185,'tatsuya','tatsuya','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (186,'tessy','tessy','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (187,'tokisimashikuka','tokisimashikuka','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (188,'touge369','touge369','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (189,'tu-yongce','Tu Yongce','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (190,'tunbolt','tunbolt','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (191,'ugume','UGUME','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (192,'wataru-matsumi','Wataru Matsumi','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (193,'wong-kok-wai','Wong Kok Wai','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (194,'wooma','WOOMA','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (195,'wotakichi-nin','WOTAKICHI(NIN)','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (196,'yamada-rokkaku','Yamada Rokkaku.','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (197,'yamamoto-ryohei','Yamamoto Ryohei','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (198,'yasushi-yamaguchi','Yasushi Yamaguchi','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (199,'yoichi-amano','Yoichi Amano','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (200,'yoko-akiyama','Yoko Akiyama','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (201,'yosuke-adachi','Yosuke Adachi','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (202,'yuji-iwasaki','Yuji Iwasaki','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (203,'yukari-shoji','Yukari Shoji','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (204,'yuki-hayashi','Yuki Hayashi','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (205,'yuki-tabata','Yuki Tabata','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (206,'yuki-yoshida','Yuki Yoshida','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (207,'yukiya-ataka','Yukiya Ataka','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (208,'yuto-suzuki','Yuto Suzuki','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (209,'yuu','yuu','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (210,'yuu-shimotsuki','Yuu Shimotsuki','limitless');
INSERT INTO illustrators (id,slug,name,source) VALUES (211,'zhiguang-liu','Zhiguang Liu','limitless');
UPDATE illustrators SET card_count=1 WHERE id=1;
UPDATE illustrators SET card_count=46 WHERE id=2;
UPDATE illustrators SET card_count=16 WHERE id=3;
UPDATE illustrators SET card_count=20 WHERE id=4;
UPDATE illustrators SET card_count=28 WHERE id=5;
UPDATE illustrators SET card_count=2 WHERE id=6;
UPDATE illustrators SET card_count=4 WHERE id=7;
UPDATE illustrators SET card_count=21 WHERE id=8;
UPDATE illustrators SET card_count=6 WHERE id=9;
UPDATE illustrators SET card_count=3 WHERE id=10;
UPDATE illustrators SET card_count=70 WHERE id=11;
UPDATE illustrators SET card_count=1 WHERE id=12;
UPDATE illustrators SET card_count=1 WHERE id=13;
UPDATE illustrators SET card_count=42 WHERE id=14;
UPDATE illustrators SET card_count=1 WHERE id=15;
UPDATE illustrators SET card_count=2 WHERE id=16;
UPDATE illustrators SET card_count=80 WHERE id=17;
UPDATE illustrators SET card_count=2 WHERE id=18;
UPDATE illustrators SET card_count=1 WHERE id=19;
UPDATE illustrators SET card_count=105 WHERE id=20;
UPDATE illustrators SET card_count=1 WHERE id=21;
UPDATE illustrators SET card_count=3 WHERE id=22;
UPDATE illustrators SET card_count=1 WHERE id=23;
UPDATE illustrators SET card_count=37 WHERE id=24;
UPDATE illustrators SET card_count=71 WHERE id=25;
UPDATE illustrators SET card_count=3 WHERE id=26;
UPDATE illustrators SET card_count=4 WHERE id=27;
UPDATE illustrators SET card_count=11 WHERE id=28;
UPDATE illustrators SET card_count=3 WHERE id=29;
UPDATE illustrators SET card_count=24 WHERE id=30;
UPDATE illustrators SET card_count=1 WHERE id=31;
UPDATE illustrators SET card_count=40 WHERE id=32;
UPDATE illustrators SET card_count=2 WHERE id=33;
UPDATE illustrators SET card_count=1 WHERE id=34;
UPDATE illustrators SET card_count=1 WHERE id=35;
UPDATE illustrators SET card_count=3 WHERE id=36;
UPDATE illustrators SET card_count=10 WHERE id=37;
UPDATE illustrators SET card_count=1 WHERE id=38;
UPDATE illustrators SET card_count=4 WHERE id=39;
UPDATE illustrators SET card_count=28 WHERE id=40;
UPDATE illustrators SET card_count=3 WHERE id=41;
UPDATE illustrators SET card_count=29 WHERE id=42;
UPDATE illustrators SET card_count=76 WHERE id=43;
UPDATE illustrators SET card_count=47 WHERE id=44;
UPDATE illustrators SET card_count=50 WHERE id=45;
UPDATE illustrators SET card_count=3 WHERE id=46;
UPDATE illustrators SET card_count=1 WHERE id=47;
UPDATE illustrators SET card_count=2 WHERE id=48;
UPDATE illustrators SET card_count=1 WHERE id=49;
UPDATE illustrators SET card_count=1 WHERE id=50;
UPDATE illustrators SET card_count=1 WHERE id=51;
UPDATE illustrators SET card_count=112 WHERE id=52;
UPDATE illustrators SET card_count=1 WHERE id=53;
UPDATE illustrators SET card_count=54 WHERE id=54;
UPDATE illustrators SET card_count=1 WHERE id=55;
UPDATE illustrators SET card_count=2 WHERE id=56;
UPDATE illustrators SET card_count=1 WHERE id=57;
UPDATE illustrators SET card_count=3 WHERE id=58;
UPDATE illustrators SET card_count=6 WHERE id=59;
UPDATE illustrators SET card_count=10 WHERE id=60;
UPDATE illustrators SET card_count=1 WHERE id=61;
UPDATE illustrators SET card_count=1 WHERE id=62;
UPDATE illustrators SET card_count=117 WHERE id=63;
UPDATE illustrators SET card_count=1 WHERE id=64;
UPDATE illustrators SET card_count=3 WHERE id=65;
UPDATE illustrators SET card_count=46 WHERE id=66;
UPDATE illustrators SET card_count=2 WHERE id=67;
UPDATE illustrators SET card_count=4 WHERE id=68;
UPDATE illustrators SET card_count=1 WHERE id=69;
UPDATE illustrators SET card_count=2 WHERE id=70;
UPDATE illustrators SET card_count=1 WHERE id=71;
UPDATE illustrators SET card_count=3 WHERE id=72;
UPDATE illustrators SET card_count=2 WHERE id=73;
UPDATE illustrators SET card_count=1 WHERE id=74;
UPDATE illustrators SET card_count=17 WHERE id=75;
UPDATE illustrators SET card_count=34 WHERE id=76;
UPDATE illustrators SET card_count=19 WHERE id=77;
UPDATE illustrators SET card_count=1 WHERE id=78;
UPDATE illustrators SET card_count=2 WHERE id=79;
UPDATE illustrators SET card_count=7 WHERE id=80;
UPDATE illustrators SET card_count=1 WHERE id=81;
UPDATE illustrators SET card_count=108 WHERE id=82;
UPDATE illustrators SET card_count=2 WHERE id=83;
UPDATE illustrators SET card_count=2 WHERE id=84;
UPDATE illustrators SET card_count=4 WHERE id=85;
UPDATE illustrators SET card_count=1 WHERE id=86;
UPDATE illustrators SET card_count=9 WHERE id=87;
UPDATE illustrators SET card_count=30 WHERE id=90;
UPDATE illustrators SET card_count=2 WHERE id=91;
UPDATE illustrators SET card_count=1 WHERE id=92;
UPDATE illustrators SET card_count=1 WHERE id=93;
UPDATE illustrators SET card_count=21 WHERE id=94;
UPDATE illustrators SET card_count=1 WHERE id=95;
UPDATE illustrators SET card_count=1 WHERE id=96;
UPDATE illustrators SET card_count=1 WHERE id=97;
UPDATE illustrators SET card_count=1 WHERE id=98;
UPDATE illustrators SET card_count=11 WHERE id=99;
UPDATE illustrators SET card_count=1 WHERE id=100;
UPDATE illustrators SET card_count=20 WHERE id=101;
UPDATE illustrators SET card_count=67 WHERE id=102;
UPDATE illustrators SET card_count=16 WHERE id=103;
UPDATE illustrators SET card_count=7 WHERE id=104;
UPDATE illustrators SET card_count=1 WHERE id=105;
UPDATE illustrators SET card_count=1 WHERE id=106;
UPDATE illustrators SET card_count=29 WHERE id=107;
UPDATE illustrators SET card_count=62 WHERE id=108;
UPDATE illustrators SET card_count=1 WHERE id=109;
UPDATE illustrators SET card_count=2 WHERE id=110;
UPDATE illustrators SET card_count=4 WHERE id=111;
UPDATE illustrators SET card_count=20 WHERE id=112;
UPDATE illustrators SET card_count=2 WHERE id=113;
UPDATE illustrators SET card_count=2 WHERE id=114;
UPDATE illustrators SET card_count=7 WHERE id=115;
UPDATE illustrators SET card_count=1 WHERE id=116;
UPDATE illustrators SET card_count=1 WHERE id=117;
UPDATE illustrators SET card_count=24 WHERE id=118;
UPDATE illustrators SET card_count=79 WHERE id=119;
UPDATE illustrators SET card_count=2 WHERE id=120;
UPDATE illustrators SET card_count=1 WHERE id=121;
UPDATE illustrators SET card_count=58 WHERE id=122;
UPDATE illustrators SET card_count=31 WHERE id=123;
UPDATE illustrators SET card_count=2 WHERE id=124;
UPDATE illustrators SET card_count=1 WHERE id=125;
UPDATE illustrators SET card_count=2 WHERE id=126;
UPDATE illustrators SET card_count=2 WHERE id=127;
UPDATE illustrators SET card_count=25 WHERE id=128;
UPDATE illustrators SET card_count=23 WHERE id=129;
UPDATE illustrators SET card_count=1 WHERE id=130;
UPDATE illustrators SET card_count=1 WHERE id=131;
UPDATE illustrators SET card_count=9 WHERE id=132;
UPDATE illustrators SET card_count=76 WHERE id=133;
UPDATE illustrators SET card_count=6 WHERE id=134;
UPDATE illustrators SET card_count=1 WHERE id=135;
UPDATE illustrators SET card_count=2 WHERE id=136;
UPDATE illustrators SET card_count=5 WHERE id=137;
UPDATE illustrators SET card_count=7 WHERE id=138;
UPDATE illustrators SET card_count=37 WHERE id=139;
UPDATE illustrators SET card_count=8 WHERE id=140;
UPDATE illustrators SET card_count=4 WHERE id=141;
UPDATE illustrators SET card_count=1 WHERE id=142;
UPDATE illustrators SET card_count=1 WHERE id=143;
UPDATE illustrators SET card_count=4 WHERE id=144;
UPDATE illustrators SET card_count=1 WHERE id=145;
UPDATE illustrators SET card_count=5 WHERE id=146;
UPDATE illustrators SET card_count=49 WHERE id=147;
UPDATE illustrators SET card_count=51 WHERE id=148;
UPDATE illustrators SET card_count=1 WHERE id=149;
UPDATE illustrators SET card_count=11 WHERE id=150;
UPDATE illustrators SET card_count=1 WHERE id=151;
UPDATE illustrators SET card_count=1 WHERE id=152;
UPDATE illustrators SET card_count=24 WHERE id=153;
UPDATE illustrators SET card_count=2 WHERE id=154;
UPDATE illustrators SET card_count=21 WHERE id=155;
UPDATE illustrators SET card_count=1 WHERE id=156;
UPDATE illustrators SET card_count=5 WHERE id=157;
UPDATE illustrators SET card_count=1 WHERE id=158;
UPDATE illustrators SET card_count=59 WHERE id=159;
UPDATE illustrators SET card_count=3 WHERE id=160;
UPDATE illustrators SET card_count=7 WHERE id=161;
UPDATE illustrators SET card_count=29 WHERE id=162;
UPDATE illustrators SET card_count=2 WHERE id=163;
UPDATE illustrators SET card_count=1 WHERE id=164;
UPDATE illustrators SET card_count=1 WHERE id=165;
UPDATE illustrators SET card_count=17 WHERE id=166;
UPDATE illustrators SET card_count=1 WHERE id=167;
UPDATE illustrators SET card_count=104 WHERE id=168;
UPDATE illustrators SET card_count=2 WHERE id=169;
UPDATE illustrators SET card_count=80 WHERE id=170;
UPDATE illustrators SET card_count=41 WHERE id=171;
UPDATE illustrators SET card_count=11 WHERE id=172;
UPDATE illustrators SET card_count=1 WHERE id=173;
UPDATE illustrators SET card_count=7 WHERE id=174;
UPDATE illustrators SET card_count=1 WHERE id=175;
UPDATE illustrators SET card_count=2 WHERE id=176;
UPDATE illustrators SET card_count=2 WHERE id=177;
UPDATE illustrators SET card_count=1 WHERE id=178;
UPDATE illustrators SET card_count=1 WHERE id=179;
UPDATE illustrators SET card_count=1 WHERE id=181;
UPDATE illustrators SET card_count=24 WHERE id=182;
UPDATE illustrators SET card_count=29 WHERE id=183;
UPDATE illustrators SET card_count=52 WHERE id=184;
UPDATE illustrators SET card_count=55 WHERE id=185;
UPDATE illustrators SET card_count=1 WHERE id=186;
UPDATE illustrators SET card_count=1 WHERE id=187;
UPDATE illustrators SET card_count=53 WHERE id=188;
UPDATE illustrators SET card_count=2 WHERE id=189;
UPDATE illustrators SET card_count=8 WHERE id=190;
UPDATE illustrators SET card_count=25 WHERE id=191;
UPDATE illustrators SET card_count=2 WHERE id=192;
UPDATE illustrators SET card_count=2 WHERE id=193;
UPDATE illustrators SET card_count=1 WHERE id=194;
UPDATE illustrators SET card_count=1 WHERE id=195;
UPDATE illustrators SET card_count=12 WHERE id=196;
UPDATE illustrators SET card_count=1 WHERE id=197;
UPDATE illustrators SET card_count=45 WHERE id=198;
UPDATE illustrators SET card_count=21 WHERE id=199;
UPDATE illustrators SET card_count=1 WHERE id=200;
UPDATE illustrators SET card_count=36 WHERE id=201;
UPDATE illustrators SET card_count=2 WHERE id=202;
UPDATE illustrators SET card_count=1 WHERE id=203;
UPDATE illustrators SET card_count=1 WHERE id=204;
UPDATE illustrators SET card_count=1 WHERE id=205;
UPDATE illustrators SET card_count=1 WHERE id=206;
UPDATE illustrators SET card_count=1 WHERE id=207;
UPDATE illustrators SET card_count=4 WHERE id=208;
UPDATE illustrators SET card_count=4 WHERE id=209;
UPDATE illustrators SET card_count=27 WHERE id=210;
UPDATE illustrators SET card_count=5 WHERE id=211;