UPDATE sets SET label = 'The Best Vol. 2', type = 'premium' WHERE id = 'PRB-02';
UPDATE sets SET label = 'The Best', type = 'premium' WHERE id = 'PRB-01';
UPDATE sets SET label = 'Heroines Edition', type = 'extra' WHERE id = 'EB-03';
UPDATE sets SET label = 'Anime 25th Collection', type = 'extra' WHERE id = 'EB-02';
UPDATE sets SET label = 'Memorial Collection', type = 'extra' WHERE id = 'EB-01';
UPDATE sets SET label = 'Adventure on Kami’s Island', type = 'booster' WHERE id = 'OP15-EB04';
UPDATE sets SET label = 'The Azure Sea’s Seven', type = 'booster' WHERE id = 'OP14-EB04';
UPDATE sets SET label = 'Carrying on His Will', type = 'booster' WHERE id = 'OP-13';
UPDATE sets SET label = 'Legacy of the Master', type = 'booster' WHERE id = 'OP-12';
UPDATE sets SET label = 'A Fist of Divine Speed', type = 'booster' WHERE id = 'OP-11';
UPDATE sets SET label = 'Royal Blood', type = 'booster' WHERE id = 'OP-10';
UPDATE sets SET label = 'Emperors in the New World', type = 'booster' WHERE id = 'OP-09';
UPDATE sets SET label = 'Two Legends', type = 'booster' WHERE id = 'OP-08';
UPDATE sets SET label = '500 Years in the Future', type = 'booster' WHERE id = 'OP-07';
UPDATE sets SET label = 'Wings of the Captain', type = 'booster' WHERE id = 'OP-06';
UPDATE sets SET label = 'Awakening of the New Era', type = 'booster' WHERE id = 'OP-05';
UPDATE sets SET label = 'Kingdoms of Intrigue', type = 'booster' WHERE id = 'OP-04';
UPDATE sets SET label = 'Pillars of Strength', type = 'booster' WHERE id = 'OP-03';
UPDATE sets SET label = 'Paramount War', type = 'booster' WHERE id = 'OP-02';
UPDATE sets SET label = 'Romance Dawn', type = 'booster' WHERE id = 'OP-01';
UPDATE sets SET label = 'Egghead', type = 'starter' WHERE id = 'ST-29';
UPDATE sets SET label = 'Green/Yellow Yamato', type = 'starter' WHERE id = 'ST-28';
UPDATE sets SET label = 'Black Marshall.D.Teach', type = 'starter' WHERE id = 'ST-27';
UPDATE sets SET label = 'Purple/Black Monkey.D.Luffy', type = 'starter' WHERE id = 'ST-26';
UPDATE sets SET label = 'Blue Buggy', type = 'starter' WHERE id = 'ST-25';
UPDATE sets SET label = 'Green Jewelry Bonney', type = 'starter' WHERE id = 'ST-24';
UPDATE sets SET label = 'Red Shanks', type = 'starter' WHERE id = 'ST-23';
UPDATE sets SET label = 'Ace & Newgate', type = 'starter' WHERE id = 'ST-22';
UPDATE sets SET label = 'Gear5', type = 'starter-ex' WHERE id = 'ST-21';
UPDATE sets SET label = 'Yellow Charlotte Katakuri', type = 'starter' WHERE id = 'ST-20';
UPDATE sets SET label = 'Black Smoker', type = 'starter' WHERE id = 'ST-19';
UPDATE sets SET label = 'Purple Monkey.D.Luffy', type = 'starter' WHERE id = 'ST-18';
UPDATE sets SET label = 'Blue Donquixote Doflamingo', type = 'starter' WHERE id = 'ST-17';
UPDATE sets SET label = 'Green Uta', type = 'starter' WHERE id = 'ST-16';
UPDATE sets SET label = 'Red Edward.Newgate', type = 'starter' WHERE id = 'ST-15';
UPDATE sets SET label = '3D2Y', type = 'starter' WHERE id = 'ST-14';
UPDATE sets SET label = 'The Three Brothers', type = 'ultra' WHERE id = 'ST-13';
UPDATE sets SET label = 'Zoro and Sanji', type = 'starter' WHERE id = 'ST-12';
UPDATE sets SET label = 'Uta', type = 'starter' WHERE id = 'ST-11';
UPDATE sets SET label = 'The Three Captains', type = 'ultra' WHERE id = 'ST-10';
UPDATE sets SET label = 'Yamato', type = 'starter' WHERE id = 'ST-09';
UPDATE sets SET label = 'Monkey D. Luffy', type = 'starter' WHERE id = 'ST-08';
UPDATE sets SET label = 'Big Mom Pirates', type = 'starter' WHERE id = 'ST-07';
UPDATE sets SET label = 'Absolute Justice', type = 'starter' WHERE id = 'ST-06';
UPDATE sets SET label = 'Film Edition', type = 'starter' WHERE id = 'ST-05';
UPDATE sets SET label = 'Animal Kingdom Pirates', type = 'starter' WHERE id = 'ST-04';
UPDATE sets SET label = 'The Seven Warlords of the Sea', type = 'starter' WHERE id = 'ST-03';
UPDATE sets SET label = 'Worst Generation', type = 'starter' WHERE id = 'ST-02';
UPDATE sets SET label = 'Straw Hat Crew', type = 'starter' WHERE id = 'ST-01';
UPDATE sets SET label = 'Promo Cards', type = 'promo' WHERE id = '569901';
UPDATE sets SET label = 'Other Products', type = 'other' WHERE id = '569801';